### ISSUE TITLE
Errors arise after clearing workspace

### ISSUE THREAD

**Issue by RJDennis** [sglyon/PlotlyJS.jl#107]
When using PlotlyJS through Atom, the following generates errors in Julia 0.5.0

using PlotlyJS
plot(rand(20))
workspace()
using PlotlyJS
plot(rand(20))

**Comment by sglyon** [comment]
Thanks for bringing this up. I tried your code and found the same issue outside of Atom using just the normal Julia REPL.

I believe that this is actually a problem with Blink.jl

When I run

```julia
using Blink
Window()
workspace()
using Blink
Window()
```

I get the same issue I get when I run your code. above.

I think I am going to close here as it isn't an issue with this package, but I encourage you to post an issue over at Blink.jl

**Comment by RJDennis** [comment]
Thanks for the quick response; posted an issue with Blink.jl
