### ISSUE TITLE
close plot window

### ISSUE THREAD

**Issue by lewisl** [sglyon/PlotlyJS.jl#109]
Using the plots.jl wrapper, close() or close("all") don't close a plot window.

Closing the plot window using close button (Mac) leads to massive runtime errors requiring ^C to break.

No documentation for close in the api.  Also, plots seems to have forgotten to document that.

Did I miss it somewhere?

**Comment by sglyon** [comment]
I believe this should work

```julia
using Plots
plotlyjs()

p = plot(sin)
close(p.o)
```

If it does, then we simply need to add a method like the following to Plots.jl:

```julia
Base.close(p::Plot{PlotlyJSBackend}) = close(p.o)
```

**Comment by lewisl** [comment]
Is that p dot zero or oh?

Also, is there a convention for the automatic handles?

Finally, where could I have looked to find this myself?  (Or only in sources?  Which file?)

Thanks.

- Lewis

On Feb 8, 2017, at 6:23 AM, Spencer Lyon <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe this should work

using Plots
plotlyjs()

p = plot(sin)
close(p.o)

If it does, then we simply need to add a method like the following to Plots.jl:

Base.close(p::Plot{PlotlyJSBackend}) = close(p.o)

-

**Comment by sglyon** [comment]
That is lower case letter oh.

I'm sorry, but I don't understand what you mean by "automatic handles". Can you explain?

The definition of the `close` method is [here](https://github.com/sglyon/PlotlyJS.jl/blob/b1ea56717e9ab6c98da8dd68a76649ffaecba612/src/displays/electron.jl#L25-L28)

**Comment by lewisl** [comment]
Where did p.o come from?

In Matplotlib you can do:

f1 = figure() # defines a plot object in variable f1

f1 is a variable that holds the plot object.  If you have multiple plots being defined then you can do f1.plot(…stuff) and later close(f1) —not f1.close().  This is what I meant by handle—some reference to the plot if you have more than one active concurrently.

On Feb 8, 2017, at 7:48 AM, Spencer Lyon <notifications@github.com<mailto:notifications@github.com>> wrote:


That is lower case letter oh.

I'm sorry, but I don't understand what you mean by "automatic handles". Can you explain?

The definition of the close method is here<https://github.com/sglyon/PlotlyJS.jl/blob/b1ea56717e9ab6c98da8dd68a76649ffaecba612/src/displays/electron.jl#L25-L28>

**Comment by sglyon** [comment]
Oh ok, I see. Thanks for explaining. 

Let's look at our example:

```julia
using Plots
plotlyjs()

p = plot(sin)
```

At this point `p` is a `Plots.Plot{PlotlyJSBackend}` object. All plots created with Plots.jl have type `Plots.Plot`. Because we are using the plotlyjs backend we get the type parameter `PlotlyJSBackend`.

The `Plots.Plot` object is defined [here](https://github.com/JuliaPlots/Plots.jl/blob/8204b51213aa1632b159e2579bd8bf4e6c00dfe9/src/types.jl#L70-L82) and has a field `o` (lower case letter) that typically  serves as a reference to the plot object from the backend of choice. 

In our example, `p.o` has type `PlotlyJS.SyncPlot`. We can then call the `Base.close` method I linked to above to close the window.

**Comment by lewisl** [comment]
OK.  I got it.

I glossed over the assignment when creating the plot.  This works.

So, this would be in the plots documentation somewhere though tbreff’s documentation, which is nice on examples, never uses an assignment.

Matplotlib, in order to stay “simple”, assumes a sort of interactive incrementalism when making charts.  You plot away and each one is automatically assigned a number.  You can use the number if you “forgot” to get a variable to hold the object.

Is there some equivalent of close(“all”)?  e.g. some constant that the code uses to mean all currently active plots?   Or some variable that holds the entire collection?  Sometimes that’s easier than keeping track of the object variables—at the end of your code you just close them all.

On Feb 8, 2017, at 7:58 AM, Spencer Lyon <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh ok, I see. Thanks for explaining.

Let's look at our example:

using Plots
plotlyjs()

p = plot(sin)

At this point p is a Plots.Plot{PlotlyJSBackend} object. All plots created with Plots.jl have type Plots.Plot. Because we are using the plotlyjs backend we get the type parameter PlotlyJSBackend.

The Plots.Plot object is defined here<https://github.com/JuliaPlots/Plots.jl/blob/8204b51213aa1632b159e2579bd8bf4e6c00dfe9/src/types.jl#L70-L82> and has a field o (lower case letter) that typically serves as a reference to the plot object from the backend of choice.

In our example, p.o has type PlotlyJS.SyncPlot. We can then call the Base.close method I linked to above to close the window.

**Comment by sglyon** [comment]
Neither Plots.jl or PlotlyJS.jl keeps a global stack of active plots like matplotlib does. 

As for the doc issue you'll have to work with @tbreloff or others in the community to either make a pull request to add that or open an issue requesting that someone else does.

**Comment by lewisl** [comment]
Good enough.  Thanks.

Close it.

On Feb 8, 2017, at 8:08 AM, Spencer Lyon <notifications@github.com<mailto:notifications@github.com>> wrote:


Neither Plots.jl or PlotlyJS.jl keeps a global stack of active plots like matplotlib does.

As for the doc issue you'll have to work with @tbreloff<https://github.com/tbreloff> or others in the community to either make a pull request to add that or open an issue requesting that someone else does.
