### ISSUE TITLE
Error showing value of type PlotlyJS.SyncPlot{PlotlyJS.ElectronDisplay}

### ISSUE THREAD

**Issue by MikaelSlevinsky** [sglyon/PlotlyJS.jl#110]
I've just started on a recent version of 0.6-dev and ran into this error.

```julia
julia> versioninfo()
Julia Version 0.6.0-dev.2749
Commit c16e252* (2017-02-10 18:39 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

julia> using PlotlyJS

julia> plot(exp,0.0,1.0)
Error showing value of type PlotlyJS.SyncPlot{PlotlyJS.ElectronDisplay}:
ERROR: TypeError: typeassert: expected AbstractString, got Symbol
```

**Comment by sglyon** [comment]
Thanks for reporting.

Things aren't quite ready for 0.6 in a number of the PlotlyJS dependencies. Once we can load all our dependencies, I will make a quick pass to change things that don't work inside this library.

Thanks

**Comment by mkborregaard** [comment]
I still have this error. @sglyon do you know which dependency throws this error?

**Comment by mkborregaard** [comment]
I'm guessing it must be Blink.jl?

**Comment by sglyon** [comment]
yep, that's right. It is in Blink.

With [this PR](https://github.com/JunoLab/Blink.jl/pull/88#issuecomment-305483268) PlotlyJS.jl works fine for me on 0.6rc2

To get it working I needed the commit in that PR plus a few others that are in master of Blink, but haven't been tagged yet.

Once I get someone to "review" that PR then I'll tag a version of blink and we should be good to go with tagged versions of all dependencies (I also have some WIP towards no deprecation warnings on 0.6 for this package, but it is just local on my machine for now)

**Comment by mkborregaard** [comment]
Awesome! I just checked out your PR, and with that it also works as a Plots backend on 0.6. That's sweet - we're hoping to up the minimum requirement on master to julia-0.6 next week :-)

**Comment by mkborregaard** [comment]
@sglyon speaking of - The plotlyjs backend for Plots is really great - I think you wrote most of that? I was thinking after the summer to do a weekends' "clean up all pending issues with the plotlyjs backend"-session, but I don't know the code very well. Any chance you'll be up for assistance/advice at that point?

**Comment by sglyon** [comment]
@mkborregaard thanks!

It was a collaborative effort between Tom and I (he wrote most of the code but I was around for assistance/advice). 

I should be able to help out -- let me know when you're getting ready to tackle it and I will give you a more concrete answer as to how much time I have.

**Comment by mkborregaard** [comment]
That's perfect! realistically we're talkin late August.
Thanks!

**Comment by ChrisRackauckas** [comment]
Isn't this fixed by https://github.com/JunoLab/Blink.jl/pull/88#issuecomment-305483268 ?

**Comment by sglyon** [comment]
Yep, thanks for catching
