### ISSUE TITLE
2D-Histogram examples are not working

### ISSUE THREAD

**Issue by bluehope** [sglyon/PlotlyJS.jl#111]
I've tried some 2D Histogram examples in
this link, https://plot.ly/julia/2D-Histogram/.

This shows errors as below.
```
LoadError: MethodError: no method matching PlotlyJS.Plot{TT<:PlotlyJS.AbstractTrace}(::Array{Array{Pair{String,B},1},1}, ::Array{Pair{String,String},1})
Closest candidates are:
  PlotlyJS.Plot{TT<:PlotlyJS.AbstractTrace}{T<:PlotlyJS.AbstractTrace}(!Matched::Array{T<:PlotlyJS.AbstractTrace,1}, ::Any; style) at /Users/bluehope/.julia/v0.5/PlotlyJS/src/PlotlyJS.jl:64
  PlotlyJS.Plot{TT<:PlotlyJS.AbstractTrace}(!Matched::PlotlyJS.AbstractTrace, ::Any; style) at /Users/bluehope/.julia/v0.5/PlotlyJS/src/PlotlyJS.jl:69
  PlotlyJS.Plot{TT<:PlotlyJS.AbstractTrace}{T}(::Any) at sysimg.jl:53
 in #plot#36(::Array{Any,1}, ::Function, ::Array{Array{Pair{String,B},1},1}, ::Vararg{Any,N}) at /Users/bluehope/.julia/v0.5/PlotlyJS/src/display.jl:75
 in plot(::Array{Array{Pair{String,B},1},1}, ::Array{Pair{String,String},1}) at /Users/bluehope/.julia/v0.5/PlotlyJS/src/display.jl:75
 in include_string(::String, ::String) at ./loading.jl:441
 in include_string(::String, ::String) at /usr/local/opt.user/julia_0.5/usr/lib/julia/sys.dylib:?
 in include_string(::Module, ::String, ::String) at /Users/bluehope/.julia/v0.5/CodeTools/src/eval.jl:32
 in (::Atom.##61#64{String,String})() at /Users/bluehope/.julia/v0.5/Atom/src/eval.jl:81
 in withpath(::Atom.##61#64{String,String}, ::String) at /Users/bluehope/.julia/v0.5/CodeTools/src/utils.jl:30
 in withpath(::Function, ::String) at /Users/bluehope/.julia/v0.5/Atom/src/eval.jl:46
 in macro expansion at /Users/bluehope/.julia/v0.5/Atom/src/eval.jl:79 [inlined]
 in (::Atom.##60#63{String,String})() at ./task.jl:60
while loading /Users/bluehope/Documents/test.jl, in expression starting on line 15
```

Would there be any works around?
Thanks!

**Comment by sglyon** [comment]
Hi @bluehope unfortunately the docs on the plotly website are very out of date. 

The documentation [here](http://spencerlyon.com/PlotlyJS.jl/) is accurate, but unfortunately doesn't contain quite as many examples.

The first example that you linked to should be replicated as follows:

```julia
plot(histogram2d(x=randn(500), y=randn(500)+1))
```

cc @jparmer

**Comment by bluehope** [comment]
@sglyon  Thanks for the reply and documentations link. 
I've tried cool example such as contour7() http://spencerlyon.com/PlotlyJS.jl/examples/contour/.
However, histrogram2d is not supported in PlotlyJS yet? or would there by any way to draw like [spy()](http://matplotlib.org/api/pyplot_api.html?highlight=spy#matplotlib.pyplot.spy) in matplotlib.

**Comment by sglyon** [comment]
Histogram2d works the same in PlotlyJS.jl as any other plotly library.  You simply need to build a trace with the `hisogram2d` type. See the example in my previous comment to get started.

 For a list of all the possible attributes you can set you can refer to the plotly.js documentation [here](https://plot.ly/javascript/reference/#histogram2d)
