### ISSUE TITLE
HTML script virus in examples

### ISSUE THREAD

**Issue by gustafsson** [sglyon/PlotlyJS.jl#113]
The antivirus Avira on OS X flags a virus in this repository:

```
Virus alert for file "/v0.5/PlotlyJS/examples/mutation.ipynb": Details:        HTML/Infected.WebPage.Gen2 ; virus ; Contains detection pattern of the HTML script virus HTML/Infected.WebPage.Gen2
```

**Comment by sglyon** [comment]
Hmm, I have no idea what this means, but I'm confident that I haven't injected any viruses into that example.

Can you provide any more information on what this means?

**Comment by gustafsson** [comment]
```
$ git clone git@github.com:sglyon/PlotlyJS.jl.git
Cloning into 'PlotlyJS.jl'...
remote: Counting objects: 2239, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 2239 (delta 23), reused 0 (delta 0), pack-reused 2190
Receiving objects: 100% (2239/2239), 11.22 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (1271/1271), done.
$ cd PlotlyJS.jl/examples
$ cp mutation.ipynb mutation2.ipynb 
cp: mutation.ipynb: Permission denied
$ ls
3d.jl            area.jl          bar.jl           box_plots.jl     contour.jl       finance.jl       histograms.jl    line_scatter.jl  maps.jl          shapes.jl        subplots.jl      ternary.jl       time_series.jl
$
```

Avira Free Antivirus "quarantined" the file and writes this in its log

```
avguard.bin[444] <Info>: Virus alert for file ".../PlotlyJS.jl/examples/mutation.ipynb": Details:        HTML/Infected.WebPage.Gen2 ; virus ; Contains detection pattern of the HTML script virus HTML/Infected.WebPage.Gen2
avguard.bin[444] <Notice>: the alert in file .../PlotlyJS.jl/examples/mutation.ipynb was handled. Action(s) taken: access denied, condition logged, file quarantined
avqmd.bin[420] <Notice>: *
avqmd.bin[420] <Notice>: File .../PlotlyJS.jl/examples/mutation.ipynb was quarantined
```
and soon afterwards `.../PlotlyJS.jl/examples/.ipynb_checkpoints/mutation-checkpoint.ipynb` gets quarantined as well.

That is all the information I know of. I'm not suggesting _you_ intentionally injected it. But a virus on your computer might have. Anyways; c98d0afbd5126d40095ac7b39e53ba73b65c2185 is clean according to my antivirus software. But 473202d18b0d52e8f32b7ab1f7ccf36e5288500b `examples/mutation.ipynb` is not. I don't know any more than that.

**Comment by sglyon** [comment]
Thanks for doing the bisect to find which commit started this!

Can you check what it looks like with the current master?

**Comment by gustafsson** [comment]
mutation is all good, but I get the same error for `examples/interactions.ipynb` instead now

**Comment by sglyon** [comment]
Hmm that's strange. I'm leaning towards calling this a false positive. Is there any way we can really figure out if it is an issue?

**Comment by gustafsson** [comment]
It triggers on something in the minified blob for plotly.js v1.19.1.

Replacing that minified blob with the latest plotly.js v1.24.2 (https://cdn.plot.ly/plotly-latest.min.js) didn't trigger my antivirus.

**Comment by sglyon** [comment]
OK, thanks for hunting it down. This new evidence really makes me think this is a false positive.

At any rate, I have some changes on a development branch that I will be merging soon. When that merge happens I will tag a new release in METADATA.jl and when users update they will get a fresh version of plotly-latest.min.js

Thanks

**Comment by sglyon** [comment]
HI @gustafsson I have updated the code base. 

I think we are ok now. 

If this issue comes up again, please feel free to reopen this issue
