### ISSUE TITLE
Error handling websocket connection

### ISSUE THREAD

**Issue by mfariacastro** [sglyon/PlotlyJS.jl#115]
Hi everyone, I am using the plotlyjs() backend with Plots.jl and I am getting some annoying warnings when trying to produce some simple plots. I believe the problem is related to plotlyjs as I do not get this warning when trying to use other backends.

This seems to be relatively harmless, as the plots are generated correctly. It is just annoying because I rely on the output printed in the console for diagnostics, and this warning message messes up part of the output.

`Error handling websocket connection:
MethodError: no method matching *(::ArgumentError, ::Blink.#msg)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:138
  *(::LightGraphs.LinAlg.Noop, ::Any) at C:\Users\mdf34\.julia\v0.5\LightGraphs\src\linalg\./graphmatrices.jl:280`

Here is a small example of code that generates the error in my REPL:

```
## Test
using Plots
plotlyjs()

nz = 4
nx = 100
labels  = Array{String}(1,nz)
images = zeros(nx,nz)

f(x::Float64, z::Float64) = z .* x

gridx = collect(linspace(0,10,nx))
gridz = collect(linspace(1,nz,nz))

for (ix,x) in enumerate(gridx)
    for (iz,z) in enumerate(gridz)
        images[ix,iz] = f(x,z)
        labels[iz] = ("z = $z")
    end
end

plot(gridx, images, linewidth=2, alpha=0.5, label=labels, xlabel="x", title="Images")
```

**Comment by sglyon** [comment]
Hey @mfariacastro thanks for opening the issue here.

I think this is a problem inside the Blink.jl package, but should be resolved with the latest registered version (see here https://github.com/JuliaLang/METADATA.jl/pull/9105)

Will you try running `Pkg.update()` and then doing your example again?

**Comment by mfariacastro** [comment]
Thanks a lot @sglyon , that indeed solved the issue!

**Comment by sglyon** [comment]
Great, glad we got it fixed.
