### ISSUE TITLE
Changing colorscale in Scatter Plots

### ISSUE THREAD

**Issue by psilva07** [sglyon/PlotlyJS.jl#117]
I'm making a scatter plot with a color gradient associated to each value:

```julia
rmsePlot = scatter(x=ValidationOutput[1:1000], y=fit[1:1000], name="Predicted Values",  mode="markers", marker_color = abs(ValidationOutput[1:1000] .- fit[1:1000]))
layout = Layout(title="True versus predicted", yaxis=attr(title="predicted"), xaxis=attr(title="true"))
plot([rmsePlot], layout)
```
This works just fine, but the colors range from gray to red, which is not very intuitive for case. I'd like to have it going from blue to red, but I'm not sure how to do it. Looking at the documentation of plotly.js it seems like this can be achieved by using `colorspace = [[0, 'rgb(0,0,255)', [1, 'rgb(255,0,0)']]` or similarly evoking predefined words such as `colorspace = "Bluered"` on the scatter properties, but neither one worked for me. Can this be done somehow or it isn't possible at this time?

**Comment by sglyon** [comment]
Hi @psilva07, yes the sis possible. To do this you need to set the `marker.color.colorscale` property.

See the example below:

```
julia> x = linspace(0, 2π, 100);

julia> y = sin.(x);

julia> colors = abs.(y);

julia>

julia> t = scatter(
           x=x, y=y, mode="markers",
           marker=attr(cmin=minimum(colors), cmax=maximum(colors), color=colors, colorscale="Bluered")
       )
scatter with fields marker, mode, type, x, and y


julia> plot(t)
```

This results in 

![newplot](https://cloud.githubusercontent.com/assets/1001948/25710342/f8c786f4-30b9-11e7-8f24-179fb6b11d17.png)

**Comment by psilva07** [comment]
Aw, I see. I have to change the marker properties, inside the scatter plot properties. Thank you so much @sglyon, that works exactly like I wanted.
