### ISSUE TITLE
Integrate with the display-backend stack

### ISSUE THREAD

**Issue by davidanthoff** [sglyon/PlotlyJS.jl#122]
I'm adding a plot pane to the julia VS Code extension. I've got it working with pretty much all plot packages, except this one here :)

The problem seems to be that this package completely ignores the display-backend stack in julia base. Essentially, if the top display on the display stack is say a ``REPLDisplay`` I guess it makes sense to show something using Electron, but if the top display on the display stack is e.g. the custom display type that we are using for the VS Code extension, wouldn't it make more sense to not muck with the ``display`` function at all, but just defer to the methods that we define in the VS Code extension?

My gut impression is that a package like PlotlyJS.jl really should never add a generic method like ``Base.display(p::ElectronPlot)`` to ``display``. Instead, if it does want to do something like a Blink window, shouldn't it add a method like say ``function display(d::REPLDisplay, v::ElectronPlot)`` to specifically change how a plot is displayed when it is shown from a REPL?

I didn't look through all the old issues to understand why the current design was picked, so I apologize if I missed something. But would be great if we can integrate things, so happy to be educated and also happy to help out to make this smooth.

**Comment by sglyon** [comment]
It would be great to integrate with vscode!

Honesty we arrived where we are now because I never took the time to learn how the "display backend stack" works. Could you help me understand a bit more(or point me to the docs)?

I'm sure there's a better way than what im doing, I just don't know what that is ;)

**Comment by davidanthoff** [comment]
Sure, happy to help!

The doc section that describes this is [here](https://docs.julialang.org/en/latest/stdlib/io-network.html#Multimedia-I/O-1).

I think the whole design with the ``AbstractPlotlyDisplay`` stuff is kind of trying to replicate what the base display-backend stuff already does, and maybe in an incompatible way. For example, it seems that in the ``__init__`` function it is once and for all decided whether electron will be used or not, based on whether the package is loaded in an IJulia session. I don't think that is how things are meant to be, instead that decision should really depend on whether the IJulia display is on the display backend stack. But I don't understand the whole idea of ``SyncPlot``, and maybe you actually need to do it that way.

Here is how I would normally think a plotting package should integrate with the display stack:
1. it should provide various ``show`` methods for all the mime types it supports. That should actually be enough for the VS Code extension to work
2. if the package wants to do some custom thing if a plot is displayed on the REPL, it should add a method ``function display(d::REPLDisplay, v::MyPlot)``. That will only be called if the REPL multimedia display is used and then an instance of ``MyPlot`` should be shown there.
3. the package should *not* add a method a la ``display(v::MyPlot)``. Adding that entirely disables the julia default display stack.

My sense about the whole electron display stuff is that that should really be implemented as a julia display type, say ``ElectronDisplay``. If one wants to use that display type, one would push it onto the display backend stack. The VS Code extension implements its own display type to capture all plotting, the code for that is [here](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/scripts/terminalserver/terminalserver.jl). The julia base section also explains that quite well.

If the electron display stuff was implemented as such a julia display, it would actually display not just PlotlyJS graphs, but graphs from any plotting package. In some sense I almost feel that the ideal setup would be that maybe the electron stuff is moved into a separate package that provides a electron based plot viewing capability?

**Comment by sglyon** [comment]
Thanks for the tips and the response. That's very helpful.

So `SyncPlot` exists only so that I can tie the Julia version of the plot (nested dictionaries) to the displayed version of the plot (displayed by the plotly javascript library).

I think that @shashi is working on WebIO.jl that should hopefully allow me to move most of my display/web interaction code out of PlotlyJS.jl

I'm not sure exactly when I will have the time to get to it, but whenever that happens I will try implementing methods for `display(::SomeDisplay, p::Union{SyncPlot,Plot})`

**Comment by sglyon** [comment]
Done!

For now, please use the master branch

```julia
] # enter pkg mode
(v1.0) pkg> checkout PlotlyJS
```

If you want save figures you can do

```
] # enter package mode
(v1.0) pkg> add https://github.com/sglyon/ORCA.jl.git#master
```

If this doesn't resolve your issue here, please reopen the issue and leave a comment describing what went wrong
