### ISSUE TITLE
Failed to precompile PlotlyJS on windows, Julia 0.5

### ISSUE THREAD

**Issue by rand5** [sglyon/PlotlyJS.jl#123]
'''
INFO: Precompiling module PlotlyJS.
WARNING: Method definition describe(AbstractArray) in module StatsBase at C:\Users\Cw\.julia\v0.5\StatsBase\src\scalarstats.jl:573 overwritten in module DataFrames at C:\Users\Cw\.julia\v0.5\DataFrames\src\abstractdataframe\abstractdataframe.jl:407.
WARNING: Method definition describe(AbstractArray) in module StatsBase at C:\Users\Cw\.julia\v0.5\StatsBase\src\scalarstats.jl:573 overwritten in module DataFrames at C:\Users\Cw\.julia\v0.5\DataFrames\src\abstractdataframe\abstractdataframe.jl:407.
ERROR: LoadError: LoadError: ArgumentError: @compat called with wrong number of arguments: (:mutable,:struct,:(GenericTrace{T <: Associative{Symbol,Any}} <: AbstractTrace))
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Cw\.julia\v0.5\PlotlyJS\src\traces_layouts.jl, in expression starting on line 4
while loading C:\Users\Cw\.julia\v0.5\PlotlyJS\src\PlotlyJS.jl, in expression starting on line 39
Failed to precompile PlotlyJS to C:\Users\Cw\.julia\lib\v0.5\PlotlyJS.ji.

 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:422
'''

Tried to update and rebuild, but same error

**Comment by rand5** [comment]
'Pkg.build("PlotlyJS")' produces the following:

==============================[ ERROR: PlotlyJS ]===============================

LoadError: LoadError: syntax: extra token "SchemaAttribute" after end of expression
while loading C:\Users\Cm7045\.julia\v0.5\PlotlyJS\deps\make_schema_docs.jl, in expression starting on line 11
while loading C:\Users\Cm7045\.julia\v0.5\PlotlyJS\deps\build.jl, in expression starting on line 6

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PlotlyJS had build errors.

 - packages with build errors remain installed in C:\Users\Cm7045\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("PlotlyJS")`
 - build a single package by running its `deps/build.jl` script

================================================================================

**Comment by sglyon** [comment]
Yes, this is a known issue on the master branch. I'll push a fix soon

**Comment by sglyon** [comment]
fixed in https://github.com/sglyon/PlotlyJS.jl/commit/e1ca789180c55090cb60791d82ab9369b21a1083

**Comment by rand5** [comment]
@sglyon, Thanks for the prompt response!
I am now running into this:

INFO: Building HttpParser
INFO: Building MbedTLS
Using system libraries...
INFO: Building PlotlyJS
==============================[ ERROR: PlotlyJS ]===============================

LoadError: LoadError: syntax: extra token "SchemaAttribute" after end of expression
while loading C:\Users\Cw\.julia\v0.5\PlotlyJS\deps\make_schema_docs.jl, in expression starting on line 11
while loading C:\Users\Cw\.julia\v0.5\PlotlyJS\deps\build.jl, in expression starting on line 6

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PlotlyJS had build errors.

 - packages with build errors remain installed in C:\Users\Cw\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("PlotlyJS")`
 - build a single package by running its `deps/build.jl` script

================================================================================
