### ISSUE TITLE
Transparent surface plots

### ISSUE THREAD

**Issue by dpsanders** [sglyon/PlotlyJS.jl#126]
The `alpha` parameter seems to have no effect for `surface` plots.

e.g. this example from the `NLSolve.jl` README:

```jl
f(x, y) = ((x+3)*(y^3-7)+18, sin(y*exp(x)-1))

surface(-5:0.05:5, -5:0.05:5, (x,y)->f(x,y)[1], alpha=0.5, zlim=(-2, 2))
surface!(-5:0.05:5, -5:0.05:5, (x,y)->f(x,y)[2], alpha=0.5)
```
(which shows that there is a continuum of solutions, by the way).

**Comment by sglyon** [comment]
Yeah, in this case you are looking for `opacity`, not `alpha`.

See docs here https://plot.ly/javascript/reference/#surface-opacity

**Comment by sglyon** [comment]
Hmm, it looks like this isn't even valid code for PlotlyJS.jl

Are you using Plots.jl to create the surface?

**Comment by dpsanders** [comment]
Ah yes, sorry, using Plots.jl.
Can Plots.jl just translate `alpha` to `opacity`?

**Comment by sglyon** [comment]
It looks like `alpha` and `opacity` are synonyms in plots.jl: https://github.com/JuliaPlots/Plots.jl/blob/cadb0f96e2adc1fe749e46998bd78e8da7c133e9/src/args.jl#L412

But by doing a quick search over `opacity` in the plotly backend it doesn't appear to be used: https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/plotly.jl

I'll close here as it seems to be an issue over there. Should be easy enough for them to fix.
