### ISSUE TITLE
Empty plots in Jupyter notebooks

### ISSUE THREAD

**Issue by ghuba** [sglyon/PlotlyJS.jl#130]
Hi,

I have noticed that in some cases, the plots in a Jupyter notebook show up empty. This issue is hard to reproduce, unfortunately. It shows up somewhat randomly. I am using Julia 0.5.0 with Chrome Version 59.0.3071.115, on macOS Sierra. My impression is that this has something to do with how the notebook is saved and reopened. The problem appears when you open the notebook. Once it works and the plots are showing, the bug no longer appears during that session while the notebook remains opened.

The fix is relatively easy though:
- Restart the kernel and clear the output
- Save the notebook
- Reload the page in Chrome
- Run all cells

This regenerates the plots.

I noticed that Chrome reports a number of errors associated with that bug. It's pretty cryptic to me though. Something with comm.

<img width="548" alt="screen shot 2017-07-14 at 9 17 17 am" src="https://user-images.githubusercontent.com/4511360/28222711-8c5465fe-687d-11e7-941d-0318b23ef0a1.png">

<img width="534" alt="screen shot 2017-07-14 at 9 17 32 am" src="https://user-images.githubusercontent.com/4511360/28222716-92163ad0-687d-11e7-8942-b77fd0796dd9.png">

**Comment by sglyon** [comment]
Hi @ghuba thanks for posting here.

Does the discussion in https://github.com/sglyon/PlotlyJS.jl/issues/89 help you at all?

After you've read that a bit will you please return and let me know in this issue so we can either close it or resolve it?

Thanks

**Comment by ghuba** [comment]
Thanks for the quick reply. I looked at #89. It does seem similar to my problem. What's the solution though? I am not using Plots.

As discussed in #89, the problem may have something to do with running

    using PlotlyJS

twice.

If I start from a clean notebook, run once, close and reopen. No problem. Then, run twice, close and reopen. The second time it fails with empty plots.

I saved the notebook when it was working (bug1) and failing (bug2). See attachment. Maybe that helps.

The bug is now reproducible with the method above. Follow these steps to reproduce:

1. Restart and clear output.
2. Save notebook.
3. Reload page in browser.
4. Run all cells. Plot works.
5. Run a second time. (Plot still works.)
5. Save notebook.
6. Close and halt notebook.
7. Reopen notebook.
8. The plot is now empty. Run all cells. The plot is still empty.

I am also attaching errors from the console in Chrome.

<img width="534" alt="screen shot 2017-07-14 at 10 56 05 am" src="https://user-images.githubusercontent.com/4511360/28224224-2a162e58-6883-11e7-8cdd-009d0c1269a5.png">


[bug.zip](https://github.com/sglyon/PlotlyJS.jl/files/1149276/bug.zip)

**Comment by sglyon** [comment]
I think you nailed it when you said:

>If I start from a clean notebook, run once, close and reopen. No problem. Then, run twice, close and reopen. The second time it fails with empty plots.

What happens behind the scenes is that when you call `using PlotlyJS` the **first time** in a notebook, Julia will inject the poorly javascript (and some Jupyter+PlotlyJS.jl specific javascript) into the notebook as a hidden output for the cell in which `using PlotlyJS` was called.

If you run this cell again, the previous outputs that contained this javascript are erased. 

This isn't a problem while you still have the browser window open as that javascript is held in memory by your browser, but as soon as you refresh the page or close/reopen the notebook that js will be lost and you'll see the errors.

So, the solution (for now) is to just be careful to not re-run the cell containing `using PlotlyJS`

Hope that makes sense!

**Comment by ghuba** [comment]
Is there a way to write code such that PlotlyJS is loaded only once? For example:
```
try
    Plot()
catch
    using PlotlyJS
end
```

**Comment by sglyon** [comment]
What I do is just call `using PlotlyJS` in a cell all by itself at the top of the notebook and then not touch that cell again

**Comment by ghuba** [comment]
That's a bit tricky honestly. I can do this. But I am using this in a class with students, etc. So, I need something more robust that does not require students to remember not to run that cell again. In a notebook, people often do "Run All" to update everything.

**Comment by sglyon** [comment]
Yeah it is super unfortunate.

I think the best alternative would be to replace

```julia
using PlotlyJS
```

with 

```julia
using PlotlyJS; PlotlyJS.init_notebook()
```

calling the `PlotlyJS.init_notebook()` function will force that javascript to be dumped into the notebook's output cell every time the cell is run so we shouldn't see that problem anymore.

Can you try that out and let me know how it goes?

**Comment by ghuba** [comment]
That does not work. I tried
```
using PlotlyJS; PlotlyJS.init_notebook()
```
and separately
```
try
    PlotlyJS.init_notebook()
catch
    eval(Expr(:using, :PlotlyJS))
end
```
But same problem. The only thing that works is not running the cell at all.

Very puzzling. I also don't understand why when I do "Restart kernel and run all" (vs Clear output) it still does not work. Should not that reload the javascript? Still, that won't work.

<img width="530" alt="screen shot 2017-07-14 at 11 53 33 am" src="https://user-images.githubusercontent.com/4511360/28226464-1a9b4c4e-688b-11e7-8ac1-7073f2b1bb5e.png">

**Comment by sglyon** [comment]
That is very puzzling. Let me take a look and report back later

**Comment by sglyon** [comment]
Ok, sorry it is my fault. What you should really have is 

```
using PlotlyJS; PlotlyJS.init_notebook(true)
```

which will force the js to be reloaded each time.

I tried this an it works for me. Can you please confirm that it also solves the problem you are facing?

**Comment by ghuba** [comment]
Yes! This works. That makes sense.

Thanks for helping.

**Comment by sglyon** [comment]
Great! No problem -- enjoy
