### ISSUE TITLE
Titles cut off of example plots in documentation 

### ISSUE THREAD

**Issue by amellnik** [sglyon/PlotlyJS.jl#131]
Is there some default styling applied to plots in the documentation now?  Titles are being cut off for me on Chrome which did not occur previously.  

![image](https://user-images.githubusercontent.com/7132414/28428234-a04b85a6-6d2d-11e7-88bc-3a13a72cc8e1.png)

**Comment by sglyon** [comment]
Good catch, should be fixed now.

I'm actually not sure what chagned, but I re-built the docs and enforced that a margin appears in all the layouts and things render ok for me.

Will you please confirm and close the issue if it looks ok to you?

**Comment by amellnik** [comment]
Looks good now, thanks!
