### ISSUE TITLE
Inconistent numeric format on logarithmic axis labels

### ISSUE THREAD

**Issue by AndiMD** [sglyon/PlotlyJS.jl#132]
Hi all,

Numeric formats for axis labels are inconsistent. See example code and plot attached.
I'm on Linux, Julia 0.6 with Plots 0.12.0,PlotlyJS 0.6.4.

```
using PlotlyJS
xdata = logspace(22, 27, 100)
ydata = 1 ./ log.(xdata)
plot(scatter(; x = xdata, y = ydata, mode = "lines"), Layout(xaxis_type = "log"))
```

![xaxis](https://user-images.githubusercontent.com/24719218/28694258-ede34ef6-7328-11e7-9475-baa63945bf2c.png)

CrossRef: [https://github.com/JuliaPlots/Plots.jl/issues/973](https://github.com/JuliaPlots/Plots.jl/issues/973)

**Comment by sglyon** [comment]
HI @AndiMD I wish I had more to say, but this seems like something better suited for the [plotly.js](https://github.com/plotly/plotly.js/) repo or even the [discussion forum](https://community.plot.ly). It seems that this is a result of how the javascript library is interpreting your data, not anything that happens on the Julia side.

**Comment by AndiMD** [comment]
@sglyon: Thanks for your response. Unfortunately, they state that "Bug reports must be accompanied with a reproducible example." and I do not know Plotly or JavaScript.

**Comment by sglyon** [comment]
It might be best to start at the discussion forum. If that doesn't seem like the right solution to you can an try the following:

So if you have a PlotlyJS plot object named `p` you can try doing 

```julia
savefig(p, "plotly_bug.html"; js=:remote)
```

to have it write out all the html/javascript needed to reproduce your plot.

Hope that helps!

**Comment by AndiMD** [comment]
@sglyon: Thanks for your recommendation, but I would rather not create yet another account in the discussion forum for (probably) just one post.

New issue:
[https://github.com/plotly/plotly.js/issues/1920](https://github.com/plotly/plotly.js/issues/1920)
