### ISSUE TITLE
HTML output points to a local copy of plotly.js

### ISSUE THREAD

**Issue by amellnik** [sglyon/PlotlyJS.jl#133]
I just noticed that when I save plots to HTML files it references a local copy of plotly:

```html
<html>
<head>
     <script src="C:\Users\amellnik\.julia\v0.6\PlotlyJS\deps\plotly-latest.min.js"></script>
</head>
...
```

Would it be acceptable to have this use the [fastly CDN](https://plot.ly/javascript/getting-started/#plotlyjs-cdn)?  We could also have it attempt to load the local version, and if it fails load the CDN copy (or the other way around).  If so, let me know and I can submit a pull.

**Comment by sglyon** [comment]
Hey @amellnik 

This is actually already implemented. The `js` keyword argument accepts symbols `:local`, `:embed`, or `:remote`. `:local` is the default and is what you see, `:embed` just dumps all the js into the html file, and `:remote` uses the cdn.

You can see the option [here in savefig](https://github.com/sglyon/PlotlyJS.jl/blob/fbb05aeee1015c3a9e6d9caa0ce6e66d8d2c9932/src/savefig.jl#L105-L114), which just hands off to [this show method](https://github.com/sglyon/PlotlyJS.jl/blob/fbb05aeee1015c3a9e6d9caa0ce6e66d8d2c9932/src/display.jl#L27-L54)

**Comment by amellnik** [comment]
Whoops -- I should have looked more closely -- thanks!
