### ISSUE TITLE
Hover text doesn't handle same-x data points

### ISSUE THREAD

**Issue by cstjean** [sglyon/PlotlyJS.jl#135]
Using Plots.jl, whether I hover over the point at `(1,1)` or `(1,2)`, it's the `b` label that shows up.

![screen shot 2017-09-09 at 09 01 40](https://user-images.githubusercontent.com/8622776/30240390-98f64df8-953d-11e7-9007-e4c03d783e49.png)

**Comment by sglyon** [comment]
If you click the icon that looks like this:

<img width="33" alt="screen shot 2017-09-13 at 9 28 34 am" src="https://user-images.githubusercontent.com/1001948/30379875-ef0c3470-9865-11e7-961e-ca1b8d0c8ca9.png">

You will be able to see the hover info for the point you are nearest to

**Comment by sglyon** [comment]
You could also click the 

<img width="39" alt="screen shot 2017-09-13 at 9 29 15 am" src="https://user-images.githubusercontent.com/1001948/30379911-0b8a5a14-9866-11e7-837f-5f4aaebeb55b.png">


icon

**Comment by cstjean** [comment]
Thank you for the heads up!
