### ISSUE TITLE
subplots throw away shape information

### ISSUE THREAD

**Issue by ashleightrinh** [sglyon/PlotlyJS.jl#138]
Is there a way to layer plots? So say I have a histogram, I want to be able to plot a line over it indicating the mean. Also maybe to have multiple histograms overlaid.

Thanks,
Ashleigh

**Comment by sglyon** [comment]
Hi @ashleightrinh!

yes this is possible.

You can just add multiple traces to the plot.

here's an example:

```julia
plot([scatter(y=50 .* rand(10)), histogram(x=10 .* rand(1000))])
```

**Comment by ashleightrinh** [comment]
Thanks Spencer,

Though is there a way to plot just a vertical line (say, at the mean)? I
have tried plotting just a point using scatter but nothing appears.

**Comment by sglyon** [comment]
Yep, check out the shapes docs: http://spencerlyon.com/PlotlyJS.jl/examples/shapes/

You are looking for using the function function to add shapes to the layout

**Comment by asbisen** [comment]
below is a dirty sample

```
using PlotlyJS

x=collect(1:100)
y=rand(100)
m=mean(y)

t0=scatter(x=x, y=y)
s=[hline(m)]

plot([t0], Layout(;shapes=s))
```

**Comment by ashleightrinh** [comment]
Thank you! I realised it does work just not when I am trying to put multiple plots next to each other. Here is the code I have

```
shape1 = [vline(mean(matrix1))]
shape2 = [vline(mean(matrix2))]
shape3 = [vline(mean(matrix3))]

data1 = histogram(x=matrix1, nbinsx=18)
data2 = histogram(x=matrix2, nbinsx=18)
data3 = histogram(x=matrix3, nbinsx=18)
```
where `<matrix1>`, `<matrix2>` and `<matrix3>` are of type `<Array{Float64,1}>`.

```
p1 = plot([data1], Layout(;shapes=shape1))
p2 = plot([data2], Layout(;shapes=shape2))
p3 = plot([data3], Layout(;shapes=shape3))
[p1 p2 p3]
```

**Comment by sglyon** [comment]
I think you are right. I don't currently have logic to combine the shapes from individual plot layouts into the final "subplotted" plot.

You could try 

```Julia
p1 = plot([data1], Layout(;shapes=shape1))
p2 = plot([data2], Layout(;shapes=shape2))
p3 = plot([data3], Layout(;shapes=shape3))
p = [p1 p2 p3]
relayout!(p, shapes=vcat(shape1, shape2, shape3))
```

But I'm worried that the locations of the shapes will not be correct...

**Comment by sglyon** [comment]
Looks like all issues here have been resolved except the subplots + shapes one, making this a dup of #100. Closing in favor of that issue.
