### ISSUE TITLE
Possible issue - Error during installation 

### ISSUE THREAD

**Issue by gtollefson** [sglyon/PlotlyJS.jl#141]
I apologize if this is not the right place to post this, I'm new to programming/GitHub. I received the following warning and error message when trying to install this package. Can you tell me if this an issue with my version of Julia, my computer, or the package itself?

WARNING: deprecated syntax "_ as an rvalue around /Users/George/.julia/v0.6/PlotlyJS/deps/make_schema_docs.jl:22".
==================================================================[ ERROR: PlotlyJS ]===================================================================

LoadError: LoadError: MethodError: Cannot `convert` an object of type String to an object of type __anon__.PlotlyJSSchemaDocsGenerator.SchemaAttribute
This may have arisen from a call to the constructor __anon__.PlotlyJSSchemaDocsGenerator.SchemaAttribute(...),
since type constructors fall back to convert methods.
while loading /Users/George/.julia/v0.6/PlotlyJS/deps/make_schema_docs.jl, in expression starting on line 227
while loading /Users/George/.julia/v0.6/PlotlyJS/deps/build.jl, in expression starting on line 6

========================================================================================================================================================
ERROR: UndefVarError: __anon__ not defined
Stacktrace:
 [1] deserialize_module(::SerializationState{IOStream}) at ./serialize.jl:754
 [2] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:695
 [3] deserialize(::SerializationState{IOStream}) at ./serialize.jl:634
 [4] deserialize_datatype(::SerializationState{IOStream}, ::Bool) at ./serialize.jl:968
 [5] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:674
 [6] deserialize(::SerializationState{IOStream}) at ./serialize.jl:634
 [7] ntuple(::Base.Serializer.##1#2{SerializationState{IOStream}}, ::Int64) at ./tuple.jl:108
 [8] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:664
 [9] deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1075
 [10] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:687
 [11] deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1075
 [12] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:687
 [13] deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1075
 [14] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:687
 [15] (::Base.Pkg.Entry.##54#55{Dict{Any,Any}})(::IOStream) at ./pkg/entry.jl:639
 [16] open(::Base.Pkg.Entry.##54#55{Dict{Any,Any}}, ::String, ::String) at ./iostream.jl:152
 [17] build!(::Array{String,1}, ::Dict{Any,Any}, ::Set{Any}) at ./pkg/entry.jl:636
 [18] build(::Array{String,1}) at ./pkg/entry.jl:650
 [19] resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:570
 [20] resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/entry.jl:479
 [21] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#resolve,Tuple{}})() at ./pkg/dir.jl:36
 [22] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#resolve,Tuple{}}, ::String) at ./file.jl:70
 [23] #cd#1(::Array{Any,1}, ::Function, ::Function) at ./pkg/dir.jl:36
 [24] resolve() at ./pkg/pkg.jl:238

**Comment by cc7768** [comment]
Hi @gtollefson.

This is a perfectly acceptable place to submit something like this.

Someone else ran into this issue recently (see https://github.com/sglyon/PlotlyJS.jl/issues/139#issuecomment-337370483). A fix has already been pushed to master and a new release will be tagged soon. In the meantime, the fix described in other issue should help (https://github.com/sglyon/PlotlyJS.jl/issues/139#issuecomment-337370945). If not, please let leave another comment describing what happened.

Cheers and welcome to github!

**Comment by gtollefson** [comment]
Thank you @cc7768.

I tried following the fix by updating Homebrew and then using checkout(), build(), and update() on PlotlyJS. This didn't work for me, it said there was nothing to update or install in terminal. I pasted this below. Atom showed an error precompiling PlotlyJS which I've taken a screen shot of and attached.

<img width="680" alt="screen shot 2017-10-22 at 10 08 44 pm" src="https://user-images.githubusercontent.com/32968172/31869421-e000f658-b775-11e7-9bcc-1ea2ca6b0226.png">

julia> Pkg.update("PlotlyJS")
INFO: Updating METADATA...
INFO: Updating PlotlyJS master...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.checkout("PlotlyJS"); Pkg.build("PlotlyJS")
INFO: Checking out PlotlyJS master...
INFO: Pulling PlotlyJS latest master...
INFO: No packages to install, update or remove
INFO: Building HttpParser
INFO: Building Homebrew
INFO: Building MbedTLS
INFO: Building SpecialFunctions
INFO: Building PlotlyJS

I also tried installing Cairo as suggested in #139 but received the following error:

julia> Pkg.add("Cairo")
INFO: Installing Cairo v0.3.1
INFO: Building Homebrew
INFO: Building Cairo
WARNING: The following packages do not have relocatable bottles, installation may fail!
Please report these packages to https://github.com/JuliaLang/Homebrew.jl:
  glib
Warning: Already linked: /Users/George/.julia/v0.6/Homebrew/deps/usr/Cellar/pcre/8.41
Error: You are using macOS 10.10.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
Error: You are using macOS 10.10.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
================================[ ERROR: Cairo ]================================

LoadError: failed process: Process(`/Users/George/.julia/v0.6/Homebrew/deps/usr/bin/brew install --ignore-dependencies glib`, ProcessExited(1)) [1]
while loading /Users/George/.julia/v0.6/Cairo/deps/build.jl, in expression starting on line 162

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Cairo had build errors.

 - packages with build errors remain installed in /Users/George/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Cairo")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

**Comment by sglyon** [comment]
Can you try the following and report back what happens?

```
Pkg.rm("PlotlyJS")
Pkg.update()
Pkg.add("PlotlyJS")
```

The newest release of the package should install correctly and not require Cairo to be installed.

**Comment by gtollefson** [comment]
Sorry for my late response. I've updated my Mac OS from Yosemite to High Sierra and am a little confused by the messages returned after installing. I ran Pkg.rm("PlotlyJS"), Pkg.update(), and Pkg.add("PlotlyJS"). I saw the following after running these commands:

julia> Pkg.rm("PlotlyJS")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating PlotlyJS master...
INFO: Computing changes...
'INFO: No packages to install, update or remove

julia> Pkg.add("PlotlyJS")
INFO: No packages to install, update or remove
INFO: Package database updated

Does it look like this installed correctly? I'm getting the following error when I try running the following:

CODE:
using Plots
using Plotly
using PlotlyJS
using Rsvg

data = [
  [
    "z" => [1 20 30; 20 1 60; 30 60 1; 50 80 -10; 1 30 20],
    "x" => ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    "y" => ["Morning", "Afternoon", "Evening"],
    "type" => "heatmap"
  ]
]
response = Plotly.plot(data, ["filename" => "labelled-heatmap", "fileopt" => "overwrite"])
plot_url = response["url"]

ERROR:
Georges-MacBook-Pro:optimize_visualizer George$ julia plots.jl 
ERROR: LoadError: MethodError: no method matching PlotlyJS.Plot(::Array{Array{Pair{String,Any},1},1}, ::Array{Pair{String,String},1})
Closest candidates are:
  PlotlyJS.Plot(!Matched::AbstractArray{T<:Union{AbstractString, Date, Number, Symbol},1}, ::AbstractArray{T,1} where T) where T<:Union{AbstractString, Date, Number, Symbol} at /Users/George/.julia/v0.6/PlotlyJS/src/convenience_api.jl:56
  PlotlyJS.Plot(!Matched::AbstractArray{T<:Union{AbstractString, Date, Number, Symbol},1}, ::AbstractArray{T,1} where T, !Matched::PlotlyJS.Layout; kind, style, kwargs...) where T<:Union{AbstractString, Date, Number, Symbol} at /Users/George/.julia/v0.6/PlotlyJS/src/convenience_api.jl:56
  PlotlyJS.Plot(::AbstractArray{T<:(AbstractArray{T,1} where T),1}, !Matched::AbstractArray{T,2} where T) where T<:(AbstractArray{T,1} where T) at /Users/George/.julia/v0.6/PlotlyJS/src/convenience_api.jl:68
  ...
Stacktrace:
 [1] #plot#36(::Array{Any,1}, ::Function, ::Array{Array{Pair{String,Any},1},1}, ::Vararg{Any,N} where N) at /Users/George/.julia/v0.6/PlotlyJS/src/display.jl:76
 [2] plot(::Array{Array{Pair{String,Any},1},1}, ::Vararg{Any,N} where N) at /Users/George/.julia/v0.6/PlotlyJS/src/display.jl:76
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /Users/George/Desktop/work_projects/optimize_visualizer/plots.jl, in expression starting on line 24

**Comment by gtollefson** [comment]
I'm realizing I may be getting ahead of myself, I'm reading the documentation more thoroughly now. PlotlyJS.jl is an interface to the plotly.js library. Does this mean that I have to install and be able to write java script? Julia is my first/only language - I'm looking for a way to produce heatmaps using only Julia.

**Comment by cc7768** [comment]
You will be able to produce plots with only julia code using `PlotlyJS.jl`. @sglyon basically wrote a julia interface to their plotting methods and he handles all of the necessary messaging between julia and javascript (unless you'd like to do something really fancy, but maybe even then).

`PlotlyJS.jl` may be a dependency of another library. When you try to remove it with `Pkg.rm`, I believe it may prevent you from doing so.

Try doing `Pkg.build("PlotlyJS")` instead. What does it return then?

If this doesn't work then try opening a terminal and inputting the command

```
rm -rf ~/.julia/v0.6/PlotlyJS
```

Then start julia and try `Pkg.update()` `Pkg.add("PlotlyJS")`.

Let us know whether this helps.

**Comment by sglyon** [comment]
Sorry for the confusion @gtollefson -- there are a lot of technologies at play here, sorry about not being more clear about how PlotlyJS.jl works.

What @cc7768  is right on. I manage all the javascript stuff, so all you need to do is write Julia code. I have just added a couple examples showing basic heatmap functionality: http://spencerlyon.com/PlotlyJS.jl/examples/heatmaps/

Hopefully you can fix your installation woes and that the heatmap examples help you get on the right track

**Comment by gtollefson** [comment]
That's great!! Thank you @sglyon for the examples. I'm looking forward to exploring them once I have installation squared away. 

I tried both of your suggestions @cc7768 . I got the same error both when I ran `Pkg.build("PlotlyJS")  ` and also `rm -rf ~/.julia/v0.6/PlotlyJS`. I got the following errors respectively:

julia> Pkg.build("PlotlyJS.jl")
INFO: Building HttpParser
INFO: Building Homebrew
INFO: Building MbedTLS
INFO: Building SpecialFunctions
INFO: Building PlotlyJS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  979k    0  979k    0     0   336k      0 --:--:--  0:00:02 --:--:--  336k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2287k  100 2287k    0     0   429k      0  0:00:05  0:00:05 --:--:--  476k

**WARNING: deprecated syntax "_ as an rvalue around /Users/George/.julia/v0.6/PlotlyJS/deps/make_schema_docs.jl:22".**

and also: 

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: Installing PlotlyJS v0.7.1
INFO: Building HttpParser
INFO: Building Homebrew
INFO: Building MbedTLS
INFO: Building SpecialFunctions
INFO: Building PlotlyJS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  979k    0  979k    0     0   433k      0 --:--:--  0:00:02 --:--:--  433k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2287k  100 2287k    0     0  1514k      0  0:00:01  0:00:01 --:--:-- 1515k

WARNING: deprecated syntax "_ as an rvalue around /Users/George/.julia/v0.6/PlotlyJS/deps/make_schema_docs.jl:22".

I didn't subsequently run Pkg.add because I got that error. Thank you so much for your help!

**Comment by cc7768** [comment]
The warning isn't a problem -- You should be good to go now.

Try the example @sglyon put up:

```julia
function heatmap1()
    plot(heatmap(z=[1 20 30; 20 1 60; 30 60 1]))
end
heatmap1()
```

**Comment by gtollefson** [comment]
@cc7768 I got this error when I ran it:

ERROR: UndefVarError: heatmap not defined
Stacktrace:
 [1] heatmap1() at ./REPL[2]:2

**Comment by cc7768** [comment]
Did you do `using PlotlyJS` first?

As long as I bring `PlotlyJS` into namespace, the above code works for me -- The error you're getting is that it doesn't know what the function `heatmap` is.

**Comment by gtollefson** [comment]
@cc7768 That was my issue, thanks! The package is now working for me! I'm using the heatmap examples now to figure out how to build my heatmap. I appreciate all of your help!

**Comment by sglyon** [comment]
Great, glad it is working for you.

Thanks for the help @cc7768
