### ISSUE TITLE
"updatemenus" support

### ISSUE THREAD

**Issue by alyst** [sglyon/PlotlyJS.jl#144]
I want to add the dropdown to the plot to turn on/off traces. I'm trying something like
```julia
plot([...],
    Layout(updatemenus=[attr(buttons=[attr(label="no map", method="restyle", args=["line.color", "red"]),
                                      attr(label="recyc", method="restyle", args=["line.color", "yellow"])])]))
```

But there's no sign of the dropdown.

A I doing something wrong or "updatemenus" are not supported at the moment?

**Comment by alyst** [comment]
Ah, sorry. Actually I see the buttons now.

**Comment by sglyon** [comment]
Excellent!

making the sliders and update menus easier to work with has been on my todo list for a while, I just haven't gotten around to it. If you are interested in contributing to that effort please let me know and we can coordinate ideas/efforts to make it happen.
