### ISSUE TITLE
Advanced heatmap features help

### ISSUE THREAD

**Issue by gtollefson** [sglyon/PlotlyJS.jl#146]
Hi,

Thank you for your recent help getting PlotlyJS up and running for me. I have a question about customizing the heatmap and any suggestions/pointers to specific documentation would be very appreciated. I have looked and haven't been able to answer my questions yet.

I've attached a screenshot of a heatmap I've created using Excel conditional formatting of an output matrix from another program. I also included a screenshot of part of that output matrix.  I'd like to recreate this heatmap using PlotlyJS. Generally, it will be around 1500 rows x 100 columns but may be smaller/larger depending upon the variable dimensions of the input matrix.

Can you suggest documentation or functionality that will allow me to import my matrix into the heatmap function to be visualized? 

Thank you!
George 

<img width="745" alt="screen shot 2017-10-13 at 12 59 56 pm" src="https://user-images.githubusercontent.com/32968172/32245171-4874d498-be51-11e7-96b5-ddd72dd7ae43.png">

<img width="641" alt="screen shot 2017-10-31 at 3 41 06 pm" src="https://user-images.githubusercontent.com/32968172/32245374-f1dcea52-be51-11e7-8a33-219ac8f27187.png">

**Comment by sglyon** [comment]
Hi @gtollefson .

I recommend reading the [heatmap examples](https://plot.ly/javascript/heatmaps/) from the plotly.js documentation (note that at the top of the page you can click to see heat map examples in other languages -- the syntax will be different for Julia, but the core concepts will be the same).

If you really want full control over every aspect of your heatmap, see the [chart attribute reference for heatmaps](https://plot.ly/javascript/reference/#heatmap).

I am going to close this issue as it is not really an issue with the library, but rather a help request to make a specific chart.

You can post here again, but I can't promise I'll be able to respond  to these types of requests quickly. Perhaps a better place to ask questions like this is the [plotly community forum](https://community.plot.ly)

Good luck!

**Comment by gtollefson** [comment]
Thank you @sglyon. Sorry for the late reply and for posting in the wrong place. I'm new to programming and appreciate your patience. I am posting my question in the plotly community forum now but will also post here in case there is no reply there. I have read the examples you suggested as well as the documentation. I'm having a lot of trouble with syntax and getting additional keys to take effect when defining a heatmap function. I want to transpose z, because the heatmap type swaps columns and rows for some reason. I've read that yflip=true may solve this but it is not affecting my graphic when I run the program. In fact, no keys have any effect. For example 'name="Title Here"'  does not produce a graphic with a title. I will attach the graphic that is produced and saved along with the code. `

#Define heatmap function
function heatmap2()
    trace = heatmap(

    z=output_for_plotly,

    )

    yflip=true,
    name="Title Here",
    text=["A-1", "A-2", "A-3", "A-4", "A-5"],
    textposition="top center",
    textfont_family="Raleway, sans-serif"
    plot(trace)

end

#Call heatmap function
heatmap2()
PlotlyJS.savefig(heatmap2(), "test_Dec15.pdf")`
[test_Dec15.pdf](https://github.com/sglyon/PlotlyJS.jl/files/1564160/test_Dec15.pdf)
I've manually created a draft of the format I would like to achieve:
<img width="643" alt="screen shot 2017-12-15 at 4 11 33 pm" src="https://user-images.githubusercontent.com/32968172/34062789-7a423356-e1bc-11e7-91b3-a6e8e133ff62.png">
