### ISSUE TITLE
Plot won't display in Atom or in Blink window

### ISSUE THREAD

**Issue by Nectarineimp** [sglyon/PlotlyJS.jl#147]
I've been trying to track an error down. There aren't any error messages to pass along. I run the following code in Atom or in the REPL and neither one produces a plot to a display.

```
using PlotlyJS
function bar1()
    data = bar(;x=["giraffes", "orangutans", "monkeys"],
                y=[20, 14, 23])
    plot(data)
end
plot1 = bar1()
```

Julia v 0.6.0
PlotlyJS v 0.7.1

**Comment by sglyon** [comment]
That's very strange. When I run your example I see a plot.

Are you running this directly at the REPL or as part of a larger script? If it is in a larger script you might need to call `display(plot1)` to have the plot show up

**Comment by Nectarineimp** [comment]
I have a new error message. I let one failed run that looked like it wasn't going to stop, run over night and got:
```
Javascript error    JSLoadError: failed to load http://127.0.0.1:9274/plotly-latest.min.js
```
And when I browse to that URI I get the correct plotly js file. So the issue has something to do with that. I have Node on my machine. Maybe that plays into it? It seems there is no timeout when it tries to create the render and it's doing it through something like node or HttpServer. Did some experiments with Michael Borregaard, and he also didn't see the problem. I have a pretty vanilla Julia/Atom setup. I was using Plots but that was working fine with other backends. I narrowed it down to PlotlyJS. If you have any suggestions on tests or ways of getting more log/error messages, I am all for tracking this down further.

**Comment by Nectarineimp** [comment]
The problem continues to be intermittent. I was able to get a run using just PlotlyJS to run, so I stopped Julia, then ran a short simple script using plots. It got to the plot() function, and then eventually returned in the plots tab "Webgl is not supported by your browser - visit http://get.webgl.org for more info" which we know isn't true because it had just worked.

**Comment by sglyon** [comment]
Hmm, I'm sorry but without an example that I can reproduce it is really hard for me to debug.

Crappy answer I know, sorry about that.

If you do learn more about the issue I'd be happy to hear it

**Comment by Nectarineimp** [comment]
I think what would help would be idea on what to do to either see what is going on, or a better understanding of the dependencies. It started with Plots. I had code that worked in Plots with a gr() backend. I had trouble with plotlyjs() backend but eventually it worked and I got great output. Then the next day I did another thing and I realized even my code from the day before did not work. This suggest there is something that was triggered in the computer environment that allowed it to work before.Then I removed Plots from the equation and just tried example code using Plotly and, sure enough, it wasn't working still. I am using Atom, but I also used the Julia REPL. In the Julia REPL it created a window using Blink but failed to populate it. However it will savefig correctly.Its narrowly contained to display, and it will sometimes work as expected.I tried display(plot1) and it produced a window but in the window it says Webgl is not supported by your browser .Its really odd - I just need more insight into what to look at in order to get past this issue. I wonder if there is something corrupt and I just need to remove and re-install some packages?
On November 9, 2017 at 11:38 AM Spencer Lyon <notifications@github.com> wrote:Hmm, I'm sorry but without an example that I can reproduce it is really hard for me to debug.
Crappy answer I know, sorry about that.
If you do learn more about the issue I'd be happy to hear it

**Comment by cc7768** [comment]
Sometimes nuking your package folder and reinstalling helps.

I don't know if this is one of those times, but it is pretty low cost to give it a try.

What OS are you on?

**Comment by Nectarineimp** [comment]
I am using Windows Enterprise, so it's a corporate laptop. Nothing else gives me trouble. And it sometimes works. I just haven't figured out the magic combination. Obviously, if I can figure that out, it give more clues as to what is broken. I just retested on the REPL and that still fails. I think I will remove and then re-install PlotlyJS and see if that helps. Maybe I will move the PlotlyJS directory out of packages and then, if the new install works, I'll diff the two directories.
On November 9, 2017 at 4:07 PM Chase Coleman <notifications@github.com> wrote:Sometimes nuking your package folder and reinstalling helps.
I don't know if this is one of those times, but it is pretty low cost to give it a try.
What OS are you on?

**Comment by Nectarineimp** [comment]
Ok I don't think it is a PlotlyJS error anymore and I am closing this. I deleted Julia,reinstalled it. I added PlotlyJS and created a graph. All was fine. I then added Plots and set PlotlyJS as the backend and created a graph and it failed. The error is in Plots. In fact, setting PlotlyJS as the backend also kicks off a  bunch of name collisions. Here are the errors I get, in case it isn't clear that Plots is the issue:

```
Javascript error	JSLoadError: failed to load http://127.0.0.1:4686/plotly-latest.min.js
try_yieldto(::Base.##296#297{Task}, ::Task) at event.jl:189
wait() at event.jl:234
wait(::Condition) at event.jl:27
wait(::Task) at task.jl:181
macro expansion at dynamic.jl:67 [inlined]
(::Atom.##47#51)(::Dict{String,Any}) at eval.jl:44
handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N} where N) at comm.jl:163
(::Atom.##11#13)() at event.jl:73
```

Stack Trace
```

Javascript error	JSLoadError: failed to load http://127.0.0.1:4686/plotly-latest.min.js
in  at base\event.jl:73
in handlemsg at Atom\src\comm.jl:163
in  at Atom\src\eval.jl:44
in macro expansion at Media\src\dynamic.jl:67 <inlined>
in wait at base\task.jl:181
in wait at base\event.jl:27
in wait at base\event.jl:234
in try_yieldto at base\event.jl:189
```

**Comment by mkborregaard** [comment]
@sglyon any hint what this might be? I've never encountered this error before.

**Comment by sglyon** [comment]
Sorry we weren't more help @Nectarineimp . Just like @mkborregaard , I've never seen this issue before, so it is quite difficult to help in the debugging.

I hope you are able to find a satisfactory resolution to your problem. Good luck!

**Comment by Nectarineimp** [comment]
I think the issue is inside of Plots. I am doing a lot more testing now. It would be good to figure out why a vanilla fresh install of julia, plots, and plotlyjs is producing undesired output (but not all the time!) :-) We will nail. It just takes persistence. Since I'm the one seeing it, its on me.Michael raised an issue about a scaling issue which might be involved. I should point out that the plot is created, and can be saved. Its just an issue with displaying it.
On November 10, 2017 at 7:44 AM Spencer Lyon <notifications@github.com> wrote:Sorry we weren't more help @Nectarineimp . Just like @mkborregaard , I've never seen this issue before, so it is quite difficult to help in the debugging.
I hope you are able to find a satisfactory resolution to your problem. Good luck!

**Comment by mkborregaard** [comment]
Ah - try and grab your plot pane in Atom and resize it - I think maybe the plot itself may be outside the window.
