### ISSUE TITLE
right side of plot is not using correct color

### ISSUE THREAD

**Issue by sschelm** [sglyon/PlotlyJS.jl#148]
Julia version 0.6.1
Atom version 1.22.0
Juno version 0.1.2
Plots version 0.13.1
PlotlyJS version 0.7.1

I was using PlotlyJS inside Juno and changed the plot pane theme to "Juno".
This is what I got.
<img width="657" alt="screen shot 2017-11-13 at 17 28 54" src="https://user-images.githubusercontent.com/13321360/32736671-48e6b1d4-c898-11e7-9a22-3a2563b34a03.png">

Please, notice the white border over the complete height of the right edge.
Checking with the default color white, I noticed that this area is cutting of the rightmost axis label as well.

I don't see this behaviour with pyplot, gr nor glvisualize.
Here's the same plot with the `gr()` backend.
<img width="667" alt="screen shot 2017-11-13 at 17 29 17" src="https://user-images.githubusercontent.com/13321360/32736730-76483f6c-c898-11e7-964d-594252a3bda7.png">

It looks to me, like there's some issue with the definition of the right side of the plot, as well as with the color there.

**Comment by sglyon** [comment]
Hmm that is odd indeed. What happens when you drag the border of the plot pane to resize it? Does the issue persist.

cc @pfitzseb who knows more about the Plot pane than I

**Comment by sschelm** [comment]
Resizing snaps the right side back again. Thanks for the tip.
Though the right side is still very close to the graph. Instead of showing the axis tick at 1800 completely, it just barely shows "180"

**Comment by sglyon** [comment]
For that I think you will need to adjust `layout.margin.r` to a larger value. You can use a [style](http://spencerlyon.com/PlotlyJS.jl/styles/) to automatically set that for you
