### ISSUE TITLE
DataFrames v0.11

### ISSUE THREAD

**Issue by sam81** [sglyon/PlotlyJS.jl#151]
Currently installing PlotlyJS v0.7.1 causes the DataFrames package to downgrade from v0.11 to v0.10 (or to not upgrade from v0.10 to v0.11). I've been unable to figure out which package is causing the downgrade, I suppose it's a package that PlotlyJS depends on, but I've checked manually all packages that PlotlyJS installs (on a blank .julia directory) against all packages that are dependent on DataFrames (using Pkg.dependents("DataFrames"), and I've been unable to find the package causing the downgrade. Probably this issue will be solved once the package ecosystem stabilizes after the DataFrames v0.11 breaking release, but I thought it may be good to open an issue in case the problem is not related to a package PlotlyJS depends on. The other package that is downgraded after installing PlotlyJS is DataArrays (from v0.7.0 to v0.6.2).

DataFrames v0.11 works fine with PlotlyJS v0.5.2

**Comment by sglyon** [comment]
Thanks for opening.

I did notice this also and in a (certainly less thorough than yours) review  I also couldn't pin it down.

If/when I come across a resolution I will let you know, please do the same

**Comment by andreasnoack** [comment]
This is unrelated to any changes in this package. It happened because of https://github.com/JuliaLang/METADATA.jl/pull/12223. @sglyon It would be great if you tag a new release because that would fix the problem.

**Comment by nalimilan** [comment]
If you don't want to make a new release, you can also just remove the upper bounds on DataFrames I added preventively to 0.7.1.

**Comment by sglyon** [comment]
Thanks @andreasnoack. I have tagged a new release. Once it is merged in METADATA this should be resolved :+1:

**Comment by sglyon** [comment]
Done! When I install PlotlyJS it comes with a DataFrames >= v0.11
