### ISSUE TITLE
Do subplots work with surfaces?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [sglyon/PlotlyJS.jl#156]
```julia
julia> using PlotlyJS

julia> x = rand(10,10);

julia> y = rand(10,10);

julia> z = rand(10,10);

julia> C = rand(10,10);

julia> s = surface(x=x,y=y,z=z,surfacecolor=C);

julia> p1 = plot(s);

julia> p2 = plot(s);

julia> display([p1 p2])
data: [
  "surface with fields surfacecolor, type, x, xaxis, y, yaxis, and z",
  "surface with fields surfacecolor, type, x, xaxis, y, yaxis, and z"
]

layout: "layout with fields margin, xaxis1, xaxis2, yaxis1, and yaxis2"
```

I may have an outdated version, but the above appears to only show one subplot.

**Comment by sglyon** [comment]
It definitely is possible (see [here](https://plot.ly/javascript/3d-subplots/)), but this library doesn't properly set the `scenes` in the layout...

This is a bug

**Comment by MikaelSlevinsky** [comment]
Thanks!

**Comment by MikaelSlevinsky** [comment]
Could you please tell me how to completely hide the axes, labels, and grids in a surface plot so that all that remains is the surface? Sorry, I'm still trying to figure my way around the documentation.

**Comment by MikaelSlevinsky** [comment]
By the way, LaTeX in titles doesn't get saved: incorrectly in HTML, absent in PDF.

**Comment by MikaelSlevinsky** [comment]
(at least for surface plots)

**Comment by sglyon** [comment]
Hi @MikaelSlevinsky, for hiding the axes/labels/grids you will need to look at the properties of the `(x|y|z)axis` listed [here](https://plot.ly/javascript/reference/#layout-scene-xaxis). After a quick scan of those properties, `visible`, `showaxeslabels`, and `showline` look promising.

Sorry about the latex issues. I would need to open a separate issue and have some example code in able to help more.
