### ISSUE TITLE
Race condition with Blink.jl v0.6.0 and onwards

### ISSUE THREAD

**Issue by sglyon** [sglyon/PlotlyJS.jl#162]
In Blink 0.6.0 electron was upgraded from 0.35.2 to 1.7.10

This somehow broke things for PlotlyJS.jl

I need to open an issue (or better yet a PR) against Blink.jl, but I haven't yet isolated the issue.

cc @pfitzseb

**Comment by pfitzseb** [comment]
The problem here seems to be that `Window()` isn't blocking and doesn't provide a callback, right?

**Comment by sglyon** [comment]
Yep, I think that’s right! 

I’m not sure why this only surfaced with the upgrade of electron though... did that become async on the electron side?

**Comment by pfitzseb** [comment]
You were probably only getting lucky, I think. At least the Blink tests always had a `sleep` statement in them (which you added 😄).

The right way forward is to make the complete Blink API blocking or take callbacks (with the latter being the much preferable option), imho.

**Comment by sglyon** [comment]
That would be great, though I don’t see why it has to be an either or. 

If we use callbacks then that can form the basis of the `async` api and we can use the callbacks to also provide a `sync` api
