### ISSUE TITLE
Build fails on julia-0.6.0

### ISSUE THREAD

**Issue by nbecker** [sglyon/PlotlyJS.jl#179]
julia-0.6.0 fedora 27 linux
Blink build already failed (reported separately), but this error from curl seem unrelated:
```
julia> Pkg.add("PlotlyJS")
INFO: Installing DocStringExtensions v0.4.3
INFO: Installing PlotlyBase v0.1.1
INFO: Installing PlotlyJS v0.10.1
INFO: Building HttpParser
INFO: Building MbedTLS
INFO: Building Blink
==========================================[ ERROR: Blink ]===========================================

LoadError: UndefVarError: Blink not defined
while loading /home/nbecker/.julia/v0.6/Blink/deps/build.jl, in expression starting on line 14

=====================================================================================================
INFO: Building PlotlyJS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 429 
=========================================[ ERROR: PlotlyJS ]=========================================

LoadError: failed process: Process(`curl -L -f -o plotschema.json 'https://api.plot.ly/v2/plot-schema?sha1'`, ProcessExited(22)) [22]
while loading /home/nbecker/.julia/v0.6/PlotlyJS/deps/build.jl, in expression starting on line 3

=====================================================================================================

==========================================[ BUILD ERRORS ]===========================================

WARNING: Blink and PlotlyJS had build errors.
```

**Comment by sglyon** [comment]
Hmm it looks like PlotlyJS had an issue on top of what was reported/fixed in blink (https://github.com/JunoLab/Blink.jl/issues/120)


I haven't seen this before.

It looks like a shell command failed n the PlotlyJS.jl build script?

Can you try running the command (below for reference) from your terminal prompt (not inside Julia):

```
curl -L -f -o plotschema.json 'https://api.plot.ly/v2/plot-schema?sha1'
```

and let us know if it works?

**Comment by nbecker** [comment]
No,
```
curl -L -f -o plotschema.json 'https://api.plot.ly/v2/plot-schema?sha1'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 429 
```

**Comment by sglyon** [comment]
Are you operating under a "non-standard" networking environment? That's vague, but I'm trying to see if you are by chance working on a remote machine, inside docker, or something else like that

**Comment by nbecker** [comment]
Nothing strange at my end, but:
```
wget  'https://api.plot.ly/v2/plot-schema?sha1'
--2018-02-21 10:07:56--  https://api.plot.ly/v2/plot-schema?sha1
Resolving api.plot.ly (api.plot.ly)... 35.190.21.88
Connecting to api.plot.ly (api.plot.ly)|35.190.21.88|:443... connected.
HTTP request sent, awaiting response... 429 TOO MANY REQUESTS
2018-02-21 10:07:56 ERROR 429: TOO MANY REQUESTS.
```

**Comment by sglyon** [comment]
Do curl or wget work for other websites from your machine?

**Comment by nbecker** [comment]
Yes, doesn't that 429 say the webserver was busy?
 ```
curl -o /dev/null https://github.com/sglyon/PlotlyJS.jl/issues/179#issuecomment-367339975
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 54727    0 54727    0     0  54727      0 --:--:-- --:--:-- --:--:-- 89569
```

**Comment by nbecker** [comment]
The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting"). A Retry-After header might be included to this response indicating how long to wait before making a new request.Feb 24, 2017

**Comment by nbecker** [comment]
Maybe it fails because I'm working at a major ISP?

**Comment by sglyon** [comment]
I think we are now officially beyond the realm of my expertise. I wish I could help more, but I don't have any experience/insight to offer. 

if you do manage to figure out a solution please let me know. If you can't find a solution and want to move forward we can adjust the build script so that it doesn't download a fresh version of the plot schema

**Comment by nbecker** [comment]
would an acceptable solution be to include the file into the project instead of using curl to grab it?

**Comment by sglyon** [comment]
I did that originally but it adds a few megabytes to the repo every time we update our version of plotly so I opted for this approach instead. 

This is the first time I’ve seen an issue with it. It’s possible that the plotly server is having a hard time today for some reason and it will work again another day

**Comment by sglyon** [comment]
We could try to load up requests.jl or http.jl and attempt a download that way. 

Can you successfully download the file using either of those packages?
