### ISSUE TITLE
savefig stacked in a while loop for saving a subplot from Plots.jl

### ISSUE THREAD

**Issue by hayatoikoma** [sglyon/PlotlyJS.jl#180]
When I tried to save a subplot generated with Plots.jl via ``savefig``, I found that it doesn't exit from [a while loop](https://github.com/sglyon/PlotlyJS.jl/blob/master/src/displays/electron.jl#L217-L221).

The code example to reproduce this problem is given in https://github.com/JuliaPlots/Plots.jl/issues/1397.

I couldn't figure out why the Blink command keep returning ``nothing``...

**Comment by sglyon** [comment]
Hmm, that is strange.

I have an updated set of frontend code that will make savefig much more reliable and performant. As long as your needs aren't extremely time sensitive, I think it might be best to wait until that is released.

**Comment by hayatoikoma** [comment]
That's great to know. As I can save the figure through directly calling ```PlotlyJS.savefig```, it is not time sensitive for me.

I hope this is going to work on your new frontend!

**Comment by sglyon** [comment]
There will be some upcoming changes for how figures can be saved very soon -- I just need to find time to push the changes through and test them.

If anyone has some time and is interested in helping me implement that, please let me know!

In the mean time I could post instructions for how to get a more reliable savefig experience -- though it will require some manual effort until the above mentioned updates are complete.

**Comment by sglyon** [comment]
savefig stack has been re-written. Please try the new stuff!

For now, please use the master branch

```julia
] # enter pkg mode
(v1.0) pkg> checkout PlotlyJS
```

If you want save figures you can do

```
] # enter package mode
(v1.0) pkg> add https://github.com/sglyon/ORCA.jl.git#master
```

If this doesn't resolve your issue here, please reopen the issue and leave a comment describing what went wrong
