### ISSUE TITLE
Error requiring IJulia from PlotlyJS

### ISSUE THREAD

**Issue by mkborregaard** [sglyon/PlotlyJS.jl#181]
There seems to be an issue with `Requires` in relation to IJulia. To reproduce
```julia
julia> using IJulia

julia> using PlotlyJS
WARNING: Error requiring IJulia from PlotlyJS:
UndefRefError: access to undefined reference
```
The order in which the packages are loaded is irrelevant.

IJulia 1.7.0 and PlotlyJS 0.10.1 on Julia 0.6.2 on a Mac.

**Comment by sglyon** [comment]
Thanks for opening. I haven't seen this. 

Does the error give any more info about line numbers or filename where the error occured?

**Comment by mkborregaard** [comment]
No, unfortunately. That's the whole error message.

**Comment by sglyon** [comment]
This issue boils down to this line right here: https://github.com/JuliaLang/IJulia.jl/blob/397d190ae68c6d61425b0239733090cd93450875/src/comm_manager.jl#L38

The `IJulia.publish` socket is only filled in inside `init` here: https://github.com/JuliaLang/IJulia.jl/blob/272b4823cd6364a0ae2cb330ac13f75569bb5d5e/src/init.jl#L83

Which appears to only run when the kernel is inited. 

I suppose I'll just have to not register the comm if `!IJulia.inited`
