### ISSUE TITLE
JupyterLab incompatibility

### ISSUE THREAD

**Issue by staticfloat** [sglyon/PlotlyJS.jl#182]
When attempting to use this from within `JupyterLab 0.31.8`, I get the following error:

```
[E 13:13:40.410 LabApp] Notebook JSON is invalid: Additional properties are not allowed (u'source' was unexpected)
    
    Failed validating u'additionalProperties' in display_data:
    
    On instance[u'cells'][0][u'outputs'][0]:
    {u'data': {u'text/html': u'<script charset="utf-8" type=\'text/javascript\'>\n
...
<many thousands of lines of javascript>
...
<p>To load again call <pre>init_notebook(true)</pre></p>\n\n'},
     u'metadata': {},
     u'output_type': u'display_data',
     u'source': u'julia'}
```

I assume this is due to problems with the `source` key in that JSON payload that is being sent; although I personally don't know where that is being generated.  This error occurs on the latest `master` of `IJulia` and `PlotlyJS`.

**Comment by sglyon** [comment]
I've seen this before too. I think the problem is inside IJulia on [this line](https://github.com/JuliaLang/IJulia.jl/blob/828b424bc1bbe4169913ee5cceb7f7a7562d7e59/src/inline.jl#L43)

I wonder if deleting that line fixes it?

**Comment by staticfloat** [comment]
Yes, it does, but now I just don't see anything.  :(

**Comment by sglyon** [comment]
Did you install the jupyterlab plotly renderer? 

https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension

I need to figure out an approach for how to do that automatically

**Comment by staticfloat** [comment]
Ah, no!  I did not!  After installing `nodejs` and then running `jupyter labextension install @jupyterlab/plotly-extension`, we are good to go!

It's too bad that you need a whole `nodejs` install and an `npm` build tree to compile all that together.

**Comment by staticfloat** [comment]
Wait, no, I'm wrong.  It still doesn't work. :/

**Comment by staticfloat** [comment]
This looks like it might be useful info though:

<img width="685" alt="screen shot 2018-02-27 at 5 12 27 pm" src="https://user-images.githubusercontent.com/130920/36764435-79cf4990-1be1-11e8-9061-7d9de4d9e679.png">

**Comment by sglyon** [comment]
That error is expected, but in jupyterlab it should be benign. 

The reason for it is that in the notebook I communicate between PlotlyJS.jl and plotly.js via the `plotlyjs_eval` comm. In Jupyterlab I display plots by talking to the `@juptyerlab/plotly-extension` that you installed above.

As long as that is installed you will still see errors in the js console, but plots _should_ show up.

As we spoke over in slack -- this did resolve the issue so I'm going to close here.
