### ISSUE TITLE
savefig areaplot

### ISSUE THREAD

**Issue by juliaccproject** [sglyon/PlotlyJS.jl#192]
Hi there,
I'm trying to save a area plot to a pdf-file. Here's the example from the docs:
```julia
using PlotlyJS
using Rsvg

function area2()
    function _stacked_area!(traces)
        for (i, tr) in enumerate(traces[2:end])
            for j in 1:min(length(traces[i]["y"]), length(tr["y"]))
                tr["y"][j] += traces[i]["y"][j]
            end
        end
        traces
    end

    traces = [scatter(;x=1:3, y=[2, 1, 4], fill="tozeroy"),
              scatter(;x=1:3, y=[1, 1, 2], fill="tonexty"),
              scatter(;x=1:3, y=[3, 0, 2], fill="tonexty")]
    _stacked_area!(traces)

    plot(traces, Layout(title="stacked and filled line chart"))
end
p=area2()
savefig(p, "./test.pdf")
```
It is saving the lines,markers and axes but the background is missing in the pdf file.
Is this a bug or am I doing something wrong?

Thank you in advance.
Best Max

**Comment by juliaccproject** [comment]
```console
Julia Version 0.6.1
Commit 0d7248e (2017-10-24 22:15 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

```console
- PlotlyJS                    0.10.2
- Blink                         0.6.2
```

**Comment by juliaccproject** [comment]
Can someone reproduce the problem?
Fresh Julia installation couldn't fix the problem for me.

**Comment by juliaccproject** [comment]
It seems like this is no plotly problem. I tried for example to let plotly write out a svg-file. Here the background appears. Converting the picture with imagemagick to eps let the background dissapear again. As a workaround I just override the fillcolor option in my scatter plots with opaque colors so the problem doesn't occur. 
Writing out eps with a transparent background directly to an eps file would be a nice thing, though.

**Comment by sglyon** [comment]
Worked without a problem for me ... Sorry that isn't too helpful but it sounds like there might be an issue on your system for some reason?

**Comment by sglyon** [comment]
Closing as savefig and display backend has been re-written.

For now, please use the master branch

```julia
] # enter pkg mode
(v1.0) pkg> checkout PlotlyJS
```

If you want save figures you can do

```
] # enter package mode
(v1.0) pkg> add https://github.com/sglyon/ORCA.jl.git#master
```

If this doesn't resolve your issue here, please reopen the issue and leave a comment describing what went wrong
