### ISSUE TITLE
hover attribute does not show x and y coordinates

### ISSUE THREAD

**Issue by mstiitb** [sglyon/PlotlyJS.jl#195]
I am new to Julia. I have been trying to plot the output of my ODE using the following statements:

`plotlyjs()`
`scatter(G0, vars=(0,1), xlims=(1.0,10.7), ylims=(-1e4,1e4), label="2nd Varicose mode", hover=["Varicose"]) `

I was expecting to see the x and y coordinates when my mouse hovered over the data points but all I see is "Varicose". I have also tried
`scatter(G0, vars=(0,1), xlims=(1.0,10.7), ylims=(-1e4,1e4), label="2nd Varicose mode", hover=["$G0.t"]) `
etc but it then lists the entire array of x values when I hover any data point. I am probably missing something trivial and would welcome help.

**Comment by cc7768** [comment]
Are you using `PlotlyJS.jl` or the `Plots.jl` package?

It would be helpful if you could provide a minimal working example so that someone can run a version of the code and help figure out what is happening. For example, the following code shows the hovered points for me -- Does it work for you?

```julia
using PlotlyJS

x = collect(linspace(0, 10, 100))
y = randn(100)

trace = scatter(;x=x, y=y)
lo = Layout(;hovermode="closest")

plot(trace, lo)
```

**Comment by mstiitb** [comment]
Thank you very much for the prompt response. I agree that I should have put a simple example to highlight the problem. I have tried your code and it works perfectly well. But if you do the following, it does not and shows the same problem that I referred to above (this is a line plot):
```
using Plots
x = collect(linspace(0, 10, 100))
y = randn(100)
plotlyjs()
plot(x,y,hover="closest")

```
Since Plots.jl is the front end and `plotlyjs()` is a call to the backend plotting software, I expected the hover mode to work similarly, but it does not. So, is it a problem with Plots.jl or am I missing something here? 

PS: How does one get the code in colour while pasting remarks here?

**Comment by cc7768** [comment]
It looks like you might not be only person with this problem -- See https://github.com/JuliaPlots/Plots.jl/issues/1590

I'm glad that my simple example worked on your machine -- The issue above makes me think that this is probably coming from the `Plots.jl` end and I don't know that there is much that can be done on this end.

To get the syntax highlighting, you can add the language name (for some subset of languages) immediately after the three ticks that begin the codeblock -- Like this:

```
\```julia <-- I added the \ so that it wouldn't interpret this as the end of codeblock
using Plots
x = collect(linspace(0, 10, 100))
y = randn(100)
plotlyjs()
plot(x,y,hover="closest") 
\``` <-- \ here for same reason as above
```

**Comment by mstiitb** [comment]
Thank you for your inputs.

**Comment by Kunz-David** [comment]
> Thank you very much for the prompt response. I agree that I should have put a simple example to highlight the problem. I have tried your code and it works perfectly well. But if you do the following, it does not and shows the same problem that I referred to above (this is a line plot):
> 
> ```
> using Plots
> x = collect(linspace(0, 10, 100))
> y = randn(100)
> plotlyjs()
> plot(x,y,hover="closest")
> ```
> 
> Since Plots.jl is the front end and `plotlyjs()` is a call to the backend plotting software, I expected the hover mode to work similarly, but it does not. So, is it a problem with Plots.jl or am I missing something here?
> 
> PS: How does one get the code in colour while writing comments here?

Do you know if there is a fix or workaround using `Plots.jl` as of now?
I am looking for a feature like this for heatmaps.

**Comment by mstiitb** [comment]
Sorry, I could not figure this out.
