### ISSUE TITLE
Not sure if this warning is yours....

### ISSUE THREAD

**Issue by lewisl** [sglyon/PlotlyJS.jl#196]
WARNING: Relying on /pkg/ is now deprecated.  Please use the package 
`AssetRegistry.jl` instead to register assets directory

This might be coming from plots.jl, plotlyjs.jl, or one of the other dependencies.   Or I might need a new Julia.

Julia 0.6.3
Plots 0.17.3
PlotlyJS 0.10.2
Blink 0.6.2
PlotlyBase 0.1.2

**Comment by sglyon** [comment]
Sorry, it is really hard for me to debug this one.

Could you try loading package, one at a time and the following order, and report where the issue is?

- PlotlyBase
- Blink
- PlotlyJS
- Plots

Thanks

**Comment by lewisl** [comment]
Well, that wouldn’t quite to do it.  Just “using Blink” doesn’t cause full compilation (the pre-compile cache leaves some work  undone).  I noticed the error at runtime for the first plot—and first use of a function from a module forces the rest of the JIT to do it’s job.  So, it appears to be caused by first use of the PlotlyJS backend—but one doesn’t directly do the import—requesting the backend must do that.

So, here is a sequence that shows the warning—hope my interpretation is correct:


julia> using Plots



julia> Plots.plot(1:10,50:59,margin=8mm)

ERROR: UndefVarError: mm not defined



julia> import Measures: mm



julia> typeof(mm)

Measures.Length{:mm,Float64}



julia> Plots.plot(1:10,50:59,margin=8mm)  # a GR chart was nicely produced in GTK terminal



julia> plotlyjs()

INFO: Loading HttpServer methods...

Plots.PlotlyJSBackend()



julia> Plots.plot(1:10,50:59,margin=8mm)

WARNING: Relying on /pkg/ is now deprecated. Please use the package

`AssetRegistry.jl` instead to register assets directory

**Comment by haotian127** [comment]
I have the same problem, too.

**Comment by lewisl** [comment]
I guess I'll just quit using PlotlyJS for a while.  It is a really nice package on Julia 0.6.

I have WebIO and Mux installed successfully and Blink.

Now, building plotlyjs fails at different points:
```
(v0.7) pkg> add PlotlyJS
 Resolving package versions...
 Installed DocStringExtensions ─ v0.4.6
 Installed PlotlyBase ────────── v0.1.2
 Installed PlotlyJS ──────────── v0.10.2
  Updating `~/.julia/environments/v0.7/Project.toml`
  [f0f68f2c] + PlotlyJS v0.10.2
  Updating `~/.julia/environments/v0.7/Manifest.toml`
  [ffbed154] + DocStringExtensions v0.4.6
  [a03496cd] + PlotlyBase v0.1.2
  [f0f68f2c] + PlotlyJS v0.10.2
  Building PlotlyJS → `~/.julia/packages/PlotlyJS/i6J4s/deps/build.log`
┌ Error: Error building `PlotlyJS`: 
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100 1329k  100 1329k    0     0   200k      0  0:00:06  0:00:06 --:--:--  261k
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100 2727k  100 2727k    0     0   243k      0  0:00:11  0:00:11 --:--:--  287k
│ WARNING: Base.Markdown is deprecated, run `using Markdown` instead
│   likely near /Users/lewis/.julia/packages/PlotlyJS/i6J4s/deps/make_schema_docs.jl:3
│ WARNING: importing deprecated binding Base.Associative into PlotlyJSSchemaDocsGenerator.
│ WARNING: Base.Associative is deprecated, use AbstractDict instead.
│   likely near /Users/lewis/.julia/packages/PlotlyJS/i6J4s/deps/make_schema_docs.jl:8
│ WARNING: importing deprecated binding Base.Nullable into PlotlyJSSchemaDocsGenerator.
│ ERROR: LoadError: LoadError: TypeError: in Type{...} expression, expected UnionAll, got typeof(Base.Nullable)
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:398
│  [6] top-level scope at none:0
│  [7] include at ./boot.jl:317 [inlined]
│  [8] include_relative(::Module, ::String) at ./loading.jl:1038
│  [9] include(::Module, ::String) at ./sysimg.jl:29
│  [10] include(::String) at ./client.jl:398
│  [11] top-level scope at none:0
│ in expression starting at /Users/lewis/.julia/packages/PlotlyJS/i6J4s/deps/make_schema_docs.jl:11
│ in expression starting at /Users/lewis/.julia/packages/PlotlyJS/i6J4s/deps/build.jl:10
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/Operations.jl:1068
```

**Comment by sglyon** [comment]
Are WebIO and Blink working properly on 0.7 now? I have tried to keep an eye on the status and may have missed the messages claiming success.

If they are ready, I will make a push to get this package up to 0.7/1.0 standards in the next few days
