### ISSUE TITLE
Error building `PlotlyJS` on 1.0.0

### ISSUE THREAD

**Issue by mgiugliano** [sglyon/PlotlyJS.jl#204]
I note that both Blink.jl and HttpParser.jl failed to build. 

Error: Error building `PlotlyJS`:
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100 1329k  100 1329k    0     0   559k      0  0:00:02  0:00:02 --:--:--  559k
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100 2724k  100 2724k    0     0   439k      0  0:00:06  0:00:06 --:--:--  389k
│ ERROR: LoadError: LoadError: UndefVarError: Markdown not defined
│ Stacktrace:
│  [1] include at ./boot.jl:317 [inlined]
│  [2] include_relative(::Module, ::String) at ./loading.jl:1038
│  [3] include(::Module, ::String) at ./sysimg.jl:29
│  [4] include(::String) at ./client.jl:388
│  [5] top-level scope at none:0
│  [6] include at ./boot.jl:317 [inlined]
│  [7] include_relative(::Module, ::String) at ./loading.jl:1038
│  [8] include(::Module, ::String) at ./sysimg.jl:29
│  [9] include(::String) at ./client.jl:388
│  [10] top-level scope at none:0
│ in expression starting at /Users/XXX/.julia/packages/PlotlyJS/i6J4s/deps/make_schema_docs.jl:3
│ in expression starting at /Users/XXX/.julia/packages/PlotlyJS/i6J4s/deps/build.jl:10
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by sglyon** [comment]
Thanks for reporting

See #201 for info on this package with new Julia versions

Hopefully the web display stack is fixed soon and we are able to upgrade this package to use it. Until then we are unfortunately a bit stuck
