### ISSUE TITLE
Manual redraw!

### ISSUE THREAD

**Issue by cstjean** [sglyon/PlotlyJS.jl#209]
It seems that each `addtraces!`, `relayout!` or `deletetraces!` call triggers a full redraw. Is there a way to prevent those, temporarily? Then users wouldn't see the intermediate states of the plots.

**Comment by cstjean** [comment]
I'm wondering if I could use `Plotly.newPlot(gd, $(lowered[:data]), $(lowered[:layout]), $(options)).then(save_svg)` somehow. I'm redrawing the whole thing with completely new data.

**Comment by sglyon** [comment]
So those three methods just hand off arguments to the [corresponding functions in plotly.js](https://plot.ly/javascript/plotlyjs-function-reference/).

It should not trigger a full re-draw, but only a partial redraw of changed elements.

The `update!` method combines `relayout!` with `restyle!` and the two are applied at the same time. Could that work for you?

**Comment by cstjean** [comment]
> It should not trigger a full re-draw, but only a partial redraw of changed elements.

It's accepting a completely fresh list of traces, and I doubt that it will do a diff with the old one. So it is a full redraw, no? One full redraw is fine with me. I just want to avoid going through the three redraws that come from `delete all traces - add new traces - relayout`

> Perhaps we need to expose the Plotly.react function?

`react!(plot, new_traces, new_layout)` does sound like what I'm looking for.

**Comment by cstjean** [comment]
Oh - I see that you were talking about `addtraces`, not `newplot`; sorry.

**Comment by sglyon** [comment]
What version of Julia are you using/targeting?

I think we can get Plotly.react in for the upcoming julia 0.7+ release if you are able to use the new julia

**Comment by cstjean** [comment]
I'm on 1.0, with PlotlyWebIO.

**Comment by cstjean** [comment]
`react!` works great, thank you!
