### ISSUE TITLE
Error building - Julia 1.0

### ISSUE THREAD

**Issue by mgiugliano** [sglyon/PlotlyJS.jl#210]
Building PlotlyJS → `~/.julia/packages/PlotlyJS/3eSkF/deps/build.log`
┌ Error: Error building `PlotlyJS`:
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100 1332k  100 1332k    0     0   543k      0  0:00:02  0:00:02 --:--:--  543k
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100 2726k  100 2726k    0     0   829k      0  0:00:03  0:00:03 --:--:--  829k
│ ERROR: LoadError: LoadError: UndefVarError: Markdown not defined
│ Stacktrace:
│  [1] include at ./boot.jl:317 [inlined]
│  [2] include_relative(::Module, ::String) at ./loading.jl:1038
│  [3] include(::Module, ::String) at ./sysimg.jl:29
│  [4] include(::String) at ./client.jl:388
│  [5] top-level scope at none:0
│  [6] include at ./boot.jl:317 [inlined]
│  [7] include_relative(::Module, ::String) at ./loading.jl:1038
│  [8] include(::Module, ::String) at ./sysimg.jl:29
│  [9] include(::String) at ./client.jl:388
│  [10] top-level scope at none:0
│ in expression starting at /Users/michi/.julia/packages/PlotlyJS/3eSkF/deps/make_schema_docs.jl:3
│ in expression starting at /Users/michi/.julia/packages/PlotlyJS/3eSkF/deps/build.jl:10
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by benjaminglass1** [comment]
Can confirm this issue on freshly compiled Julia 1.0, running on Arch Linux.

**Comment by sglyon** [comment]
PLease see https://github.com/sglyon/PlotlyJS.jl/pull/208

**Comment by sglyon** [comment]
For now, please use the master branch

```julia
] # enter pkg mode
(v1.0) pkg> checkout PlotlyJS
```

If you want save figures you can do

```
] # enter package mode
(v1.0) pkg> add https://github.com/sglyon/ORCA.jl.git#master
```

If this doesn't resolve your issue here, please reopen the issue and leave a comment describing what went wrong
