### ISSUE TITLE
UndefVarError: plotattributes not defined

### ISSUE THREAD

**Issue by Navrique** [sglyon/PlotlyJS.jl#211]
Hi all, 
everything is in the title. Nothing more on the REPL. 
I am on Julia 1.0  and MacOS. The Plots backend plotlyjs() is running but I run in trouble when trying to make a simple plots
`julia> plotlyjs()
Plots.PlotlyJSBackend()
julia> a=[1,3,24,4]
4-element Array{Int64,1}:
  1
  3
 24
  4
julia> b=[6, 1, 7, 9]
4-element Array{Int64,1}:
 6
 1
 7
 9
julia> plot(a,b)
ERROR: UndefVarError: plotattributes not defined`

**Comment by sglyon** [comment]
This is an issue for Plots.jl
