### ISSUE TITLE
Can't close plot windows programmatically

### ISSUE THREAD

**Issue by lewisl** [sglyon/PlotlyJS.jl#220]
Used to work via Plots.  You don't want to support Plots or they don't want to support PlotlyJS.  I don't  want to get in the middle.  Each to their own.

example:
```
function bar1()
           data = bar(;x=["giraffes", "orangutans", "monkeys"],
                       y=[20, 14, 23])
           plot(data)
       end
bar1 (generic function with 1 method)
bar1()
```

A lovely bar chart appears.

It can't be closed.  None of the examples or any of the documentation show a plot window being closed.

I can't even find the word "close" in any of the source files.  Guess that is not supported.

I realize Plotly to the web doesn't need close:  close the tab or browser window.

Likewise in Jupyter:  there is a cell that displays and there is nothing to close.

I thought the point of PlotlyJS was to provide a wrapper around Plotly for local use by providing an Electron window. If so, one needs to be able to close that window.

I would be wrong;  I'll accept that.  I really liked PlotlyJS when it worked with Plots API.  If that is no longer going to be supported, no worries.  Moving on....

**Comment by sglyon** [comment]
Yep, you're right. I left this out when I updated the display backend. 

Will fix soon

Thanks for brining it up
