### ISSUE TITLE
Dynamical plotting with extendtraces! in Julia 0.7

### ISSUE THREAD

**Issue by kleskjr** [sglyon/PlotlyJS.jl#223]
Hi, I just updated to Julia 0.7 to test the code and noticed that the dynamical plotting does no longer work. Here is a minimal example that updates the plot every 0.1 seconds in Julia 0.6 but fails to show anything in 0.7:

```
using PlotlyJS
scatter1 = scatter(x=[],y=[])
plt = plot([scatter1])
display(plt)

for i=1:10
    extendtraces!(plt, x=[[i]], y=[[randn()]], [1])
    sleep(.1)
end

display(plt)
```
Running `display(plt)` once again at the end, shows the final plot. Are there some changes in the API that have escaped my attention?

**Comment by sglyon** [comment]
Hmm, this is certainly meant to work. Where are you running the code?

When i run your sample code (thank you very much for posting a simple example I could run!)  it works for me both in the REPL and in Jupyter notebook. See gif below

![plot_animation_jupyter](https://user-images.githubusercontent.com/1001948/45549270-40648480-b7f5-11e8-8d81-2f199111cd87.gif)

![plot_animation](https://user-images.githubusercontent.com/1001948/45549284-4bb7b000-b7f5-11e8-9e1e-5103441a8bd2.gif)

**Comment by kleskjr** [comment]
Thanks for the quick reply! Yes, indeed it works in REPL. I have tried so far Atom/Juno and running the script through `julia script.jl` in terminal. Both these methods failed.

**Comment by sglyon** [comment]
So right now communication in Juno is broken. This is a known issue. This PR needs to be resolved/merged before that will be fixed: https://github.com/JuliaGizmos/WebIO.jl/pull/187

Were you able to get any plots to show up when running `julia script.jl` from the terminal?

**Comment by kleskjr** [comment]
No, there was no success running in `julia script.jl` from the terminal, the Electron window didn't show up. If I put 

```
using Blink
w = Window()
```
at the begining of the script, the window appears, but still no plotting.

**Comment by sglyon** [comment]
OK so the problem with the script is that I define a method

```
display(::REPL.REPLDisplay, ::SyncPlot)
```

that opens a blink window and plots within it.

But the `REPL.REPLDisplay` is only attached when the REPL is active (e.g. not when running a script).

I'm not sure what we should be doing to display plots created in a script, or even if we should try to do that. 

Perhaps we should make a new function `display_blink(::SyncPlot)` that opens the blink window and plots in it. We would then have 

```julia
display(::REPL.REPLDisplay, p::SyncPlot) = display_blink(p)
```

but users could also call `display_blink(p)` in a script to see their plot.

What do you think?

**Comment by sglyon** [comment]
So the display_blink method doesn't yet exist. My proposal was to create it and forward on the REPL display method the new one. 

I used to define just display(::SyncPlot) but that clobbered the Julia display system in environments like vs code 

Would you be ok calling display_blink in your scripts if such a method were to exist?

**Comment by kleskjr** [comment]
yes, sure. calling `display_blink` would be fine with me. Should I do a PR for that?

**Comment by sglyon** [comment]
Yes, that’d be great!

I think we need to rename the existing method `display_blink` and then redefine `display(::REPLDisplay, ::SyncPlot)` to call the new `display_blink`

**Comment by sglyon** [comment]
Looks awesome, thank you!
