### ISSUE TITLE
ColorBrewer palettes not working in PlotlyJS v0.11.1

### ISSUE THREAD

**Issue by sam81** [sglyon/PlotlyJS.jl#225]
up to PlotlyJS v0.10.2 I was able to use ColorBrewer palettes as in the code example below, but with PlotlyJS v0.11.1 all plotting symbols appear black:

    using ColorBrewer, PlotlyJS
    cls = palette("Set1", 3)
    ln1 = scatter(;x=rand(10), y=rand(10), mode="markers", line_color=cls[1])
    ln2 = scatter(;x=rand(10), y=rand(10), mode="markers", line_color=cls[2])
    plot([ln1, ln2])

**Comment by sglyon** [comment]
Thanks for reporting!

Fixed in https://github.com/sglyon/PlotlyBase.jl/commit/477f8612228a85674ae978b500320c63f7f44c56

**Comment by sam81** [comment]
great thanks! Closing the issue since it's been fixed.
