### ISSUE TITLE
Cones and streamtubes

### ISSUE THREAD

**Issue by truefalsename** [sglyon/PlotlyJS.jl#227]
Hello,

is there a way to plot 3d cones (https://plot.ly/javascript/cone-plot/) and streamtubes (https://plot.ly/javascript/streamtube-plot/) with Julia's PlotlyJS? I couldn't find the the corresponding functions (analogous of scatter3d() for instance).

Thank you for your help!

**Comment by sglyon** [comment]
You should be able to follow the examples from the website.

Here's the first cone example:


```
data = cone(x=[1], y=[1], z=[1], u=[1], v=[1], w=[0])
layout = Layout(scene_camera_eye=attr(x=-0.76, y=1.8, z=0.92)
plot(data, layout)
```

**Comment by truefalsename** [comment]
Hello,

thank you for your reply. From what I see, the function "cone" is **not defined** (PlotlyBase does not contain it, apparetly), see screenshot in attachment. I can set up a dictionary and pass it to GenericTrace to get a plot done, but it seems weird that some functions are missing. For instance, I can't find streamtube either. Again, the dictionary workaround works. 
 
![screen shot 2018-09-20 at 08 56 07](https://user-images.githubusercontent.com/15799690/45798719-92088580-bcb3-11e8-9709-a7ae60725736.jpg)

**Comment by sglyon** [comment]
Ahh  I'm sorry. 

Will you please try updating your packages? That cuntuin may have been added in a recently released version of PlotlyBase

It did work for me locally (where I have the latest version), so hopefully it also works for you!

Please let us know how it goes.

**Comment by truefalsename** [comment]
Yes, works on the latest version. Thanks!
