### ISSUE TITLE
Juno compatibility

### ISSUE THREAD

**Issue by pfitzseb** [sglyon/PlotlyJS.jl#229]
Hey, just a heads up: The possibility to load local files in the plot pane (used in https://github.com/sglyon/PlotlyJS.jl/commit/69a6da0571fd60e7010f436c90b767991dc1c619) will be disabled with the next release of julia-client due to security problems.

Two possible workarounds:
1. Remove this method and use WebIO instead (which I hope to have fully working with the next Juno release).
2. Load the js file into Julia and interpolate it into the string you send to Juno.

**Comment by sglyon** [comment]
Thanks for the heads up!

I use WebIO for all the other display integrations, so as soon as it is ready to go in Juno we can remove the code you linked to and just use WebIO everywhere!
