### ISSUE TITLE
Blank plots

### ISSUE THREAD

**Issue by GlenHenshaw** [sglyon/PlotlyJS.jl#245]
Using MacOS 10.14, Julia 1.0.1 (2018-09-29). From a new Julia terminal,

    julia> using Plots
    julia> plotlyjs()
    julia> t=0:0.01:pi;
    julia> x=sin.(t);
    julia> plot(t,x)

brings up a plot window with axes, but no actual plot line. Also, the axes are not properly scaled for the (invisible) data being plotted. However,

    julia> plotly()
    julia> plot(t,x)

works as expected, as do

    julia> gr()
    julia> plot(t, x)

and

    julia> pyplot()
    julia> plot(t, x)

**Comment by cc7768** [comment]
Are you able to make the plot using just `PlotlyJS`

```
using PlotlyJS

t = 0:0.01:pi
x = sin.(t)
plot(scatter(;x=t, y=x))
```

I suspect this isn't a problem with the PlotlyJS library, but rather that the backend on Plots has not yet been updated. There are a few issues open. For starters read: https://github.com/JuliaPlots/Plots.jl/issues/1749. I'm sure that any help you can give to getting the backend updated would be greatly appreciated.

**Comment by GlenHenshaw** [comment]
OK, yes, this does work when using `PlotlyJS` directly. Thanks.

**Comment by sglyon** [comment]
This issue was fixed in another package. Please update and enjoy!
