### ISSUE TITLE
Blink/Atom/Electron not connecting properly to PlotlyJS

### ISSUE THREAD

**Issue by nicrummel** [sglyon/PlotlyJS.jl#253]
**Describe the bug**

I was plotting an interactive plot using restyle, yesterday. I saved the plot to a json, then attempted to display from the json. Now, PlotlyJS will only show a which window with display(). I have nuked my package folder in ~/.julia/packages. I have reinstalled julia from a dmg. I have tried to clean my machine of any files mentioning Atom/Blink/Electron/PlotlyJS and then reinstall from scratch. Nothing seems to help. Blink will load windows with buttons and so forth properly, but PlotlyJS cannot connect to it properly. 

**Version info**
1. 
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake
2.
Status `~/.julia/environments/v1.0/Project.toml`
  [ad839575] Blink v0.8.1
  [631607c0] CMake v1.1.0
  [336ed68f] CSV v0.4.2
  [a93c6f00] DataFrames v0.14.1
  [a1bb12fb] Electron v0.3.0
  [7073ff75] IJulia v1.14.1
  [682c06a0] JSON v0.19.0
  [47be7bcc] ORCA v0.2.0
  [f0f68f2c] PlotlyJS v0.12.0
  [37e2e46d] LinearAlgebra 
  [de0858da] Printf 
  [10745b16] Statistics

**Comment by JobJob** [comment]
Does this fix it for you: `using Pkg; Pkg.add(PackageSpec(name="WebIO", version="v4.4.2"))`

**Comment by nicrummel** [comment]
Much thanks 🙏🏻!!! This fixed my issue

**Comment by sglyon** [comment]
Thanks. 

This might work on master of PlotlyJS and current release of WebIO. See #254 for progress.
