### ISSUE TITLE
No Output in Notebook (Julia v1.0.2)

### ISSUE THREAD

**Issue by versipellis** [sglyon/PlotlyJS.jl#255]
Blink v0.8.1 and WebIO v0.6.0, as well as WebIO v0.4.2.

Debugger shows as having executed the cell properly.

    Status `~/.julia/environments/v1.0/Project.toml`
  [ad839575] Blink v0.8.1
  [336ed68f] CSV v0.4.3
  [159f3aea] Cairo v0.5.6
  [a93c6f00] DataFrames v0.14.1
  [1313f7d8] DataFramesMeta v0.4.0
  [5721bf48] DataVoyager v0.3.1
  [7073ff75] IJulia v1.14.1
  [739be429] MbedTLS v0.6.6
  [2bd173c7] NodeJS v0.5.1
  [f0f68f2c] PlotlyJS v0.12.0
  [612083be] Queryverse v0.1.0
  [6f49c342] RCall v0.13.0
  [0f1e0344] WebIO v0.4.2
  [c2297ded] ZMQ v1.0.0

**Comment by sglyon** [comment]
I'm sorry for this.

It is strange to me that this happens on WebIO#0.4.2 also when other have reported success.

Can you provide any more details about the issue? Are you in jupyterlab or notebook? which operating system? Example plotting code? etc...

**Comment by versipellis** [comment]
Any more details or information I could provide to help debug this?

**Comment by versipellis** [comment]
Checked again with PlotlyJS v.0.12.1, Blink v0.8.1, and WebIO v0.6.0, still doesn't work, although in the REPL it works as per #254.

**Comment by sglyon** [comment]
Oh man I was hoping that would have fixed things...bummer. 

Could you try removing the related packages (perhaps ijulia too) and reinstalling?

Not sure what is causing the issue, but perhaps flushing out the package installs might help.

**Comment by barche** [comment]
I get the same, no output on a Jupyter notebook, using:
```
  [ad839575] Blink v0.9.0
  [7073ff75] IJulia v1.14.1
  [510215fc] Observables v0.2.3
  [a03496cd] PlotlyBase v0.2.5
  [f0f68f2c] PlotlyJS v0.12.1
  [0f1e0344] WebIO v0.6.1
  [104b5d7c] WebSockets v1.1.0
  [cc8bc4a8] Widgets v0.4.3
```

I removed the .julia/packages directory and instantiated the environment again, and still the same.

**Comment by versipellis** [comment]
> 
> 
> Oh man I was hoping that would have fixed things...bummer.
> 
> Could you try removing the related packages (perhaps ijulia too) and reinstalling?
> 
> Not sure what is causing the issue, but perhaps flushing out the package installs might help.

Already tried the whole "reinstall Julia" thing :|

**Comment by sglyon** [comment]
I'm sorry all, I don't have a great sense of what is going on here and won't have the time to personally debug for a while (because I can't replicate the issue)

If anyone here would like to spearhead the effort to fix the problem I'd be very grateful and would be happy to review/merge a pull request that fixes the problem

**Comment by barche** [comment]
I would love to help, but I don't see any error messages, so I'm not sure where to start looking.

**Comment by sglyon** [comment]
Do you get any error messages in the web browser console?

**Comment by amellnik** [comment]
I just realized that I'm seeing the same thing on my home Ubuntu machine, although we had a few Ubuntu machines where this was working at work.  The only hint I see is a line in the js console: `Jupyter WebIO extension detected, not mounting.` every time I try to plot something.

**Comment by barche** [comment]
I get the same message. In addition, upon creating a new notebook and before even loading PlotlyJS, I see this:
```
Source map error: request failed with status 404
Resource URL: http://localhost:8888/nbextensions/webio/main.js?v=20181211164557
Source Map URL: main.js.map[Learn More]
```

WebIO still seems to work though, at least I can use Interact to create a slider.

**Comment by versipellis** [comment]
I get the same as @barche:

```
ource map error: request failed with status 404
Resource URL: http://localhost:8888/nbextensions/webio/main.js?v=20181211121735
Source Map URL: main.js.map[Learn More]
```

**Comment by sglyon** [comment]
I wonder if it has anything to do with a version of the jupyter notebook.

Perhaps @amellnik is in a good position to test this hypothesis because he has access computers where it is both working and not working?

**Comment by amellnik** [comment]
It works on jupyter `4.4.0`, I'll check the non-working on this evening.

**Comment by versipellis** [comment]
I'm on `jupyter 5.0.0`, not working.

**Comment by amellnik** [comment]
My home machine is also on `4.4.0` so it is probably something else.

**Comment by sglyon** [comment]
@shashi, any ideas what could be causing this. Could there be an error in how I am using webio?

**Comment by lwabeke** [comment]
Note sure if I have the exact same problem, but I also have similar problems but getting the error message:
`Loading WebIO Jupyter extension on an ad-hoc basis. Consider enabling the WebIO nbextension for a stabler experience (this should happen automatically when building WebIO).
`
I tried rebuilding WebIO, but no effect.

I have noticed that at times the error message doesn't show up and it looks like it was just a blank output. Closing the notebook and opening it up again, then suddenly I could see the error message.

In the Browser Console I get the error message:
```
Unhandled Promise Rejection: Error: undefined is not an object (evaluating 'WebIO.CommandSets')
  Evaluating http://localhost:8889/assetserver/c1370c191b2bf442feb7eb5b3caf02f581ddcf6d-plotly_webio.bundle.js
  Loading /assetserver/c1370c191b2bf442feb7eb5b3caf02f581ddcf6d-plotly_webio.bundle.js

```

**Comment by amellnik** [comment]
One more hint is that on the computer where it works there's some interesting errors in the console:

![screen shot 2018-12-14 at 10 18 42 am](https://user-images.githubusercontent.com/7132414/50020095-be1d6500-ff89-11e8-8c03-20f2469769c5.png)

**Comment by sglyon** [comment]
This really smells like a webio error. Maybe posting that screenshot over there would get us a quicker expert opinion?

**Comment by shashi** [comment]
@travigd any ideas?

**Comment by travigd** [comment]
Couple of observations.
* The source map 404 is fine. The bundles Javascript has references (in comments) to a source map file and chrome can't find it since we're not including it in the distributed files.
* I've still yet to fix the CommandSets thing (https://github.com/JuliaGizmos/WebIO.jl/issues/227). This doesn't explain why `0.4.x` doesn't work.
* I think you'll have better luck with `0.4.x` for now.

I'm inordinately busy right now but can try to at least fix the CommandSets things and see if I can replicate this.

**Comment by sglyon** [comment]
Thanks @travigd 


I did remove the reference to CommandSets in this commit: https://github.com/sglyon/PlotlyJS.jl/commit/c54b847d36010621fcedf352d5eaea5d1c6ffb5a

Does my "fix" introduce new bugs?

**Comment by travigd** [comment]
@sglyon Looks like you deleted it in the JS code but not in the julia code: https://github.com/sglyon/PlotlyJS.jl/blob/4f526e0eeff644fb3c48e0b234b75b9153fd67d5/src/display.jl#L101 

That's definitely a decent work around for now:tm: but I'd like to implement an idiomatic way to that kind of thing as well (without using globals).

**Comment by JobJob** [comment]
I haven't looked into this deeply, but I had basically all the above problems, and switching to PlotlyJS#master (at current commit: 2c1f60c537011aee2756579514fb29a2b247aa94) and tagged WebIO (v0.7.0), then:

* build WebIO
* restart kernel and clear output (in notebook "kernel" menu)
* save notebook
* restart Jupyter server
* browser refresh the notebook (ctrl/cmd-shift-r)

Seems to solve the problems for me.

**Comment by DhruvaSambrani** [comment]
> Note sure if I have the exact same problem, but I also have similar problems but getting the error message:
> `Loading WebIO Jupyter extension on an ad-hoc basis. Consider enabling the WebIO nbextension for a stabler experience (this should happen automatically when building WebIO). `
> I tried rebuilding WebIO, but no effect.
> 
> I have noticed that at times the error message doesn't show up and it looks like it was just a blank output. Closing the notebook and opening it up again, then suddenly I could see the error message.
> 
> In the Browser Console I get the error message:
> 
> ```
> Unhandled Promise Rejection: Error: undefined is not an object (evaluating 'WebIO.CommandSets')
>   Evaluating http://localhost:8889/assetserver/c1370c191b2bf442feb7eb5b3caf02f581ddcf6d-plotly_webio.bundle.js
>   Loading /assetserver/c1370c191b2bf442feb7eb5b3caf02f581ddcf6d-plotly_webio.bundle.js
> ```

This is the EXACT same thing that I'm facing.

Windows 10
jupyter-core                                    4.4.0
jupyter-contrib-nbextensions         0.5.1
WebIO                                             0.8.1
PlotlyJS                                            0.12.3
Plots                                                0.24.0
IJulia                                                1.18.1

**Comment by DhruvaSambrani** [comment]
https://github.com/JuliaGizmos/WebIO.jl/issues/236#issuecomment-484428662
https://github.com/JuliaGizmos/WebIO.jl/pull/276#issue-271739630

It seems like this was a WebIO issue, and once the pull request is merged, it should work.

**Comment by DhruvaSambrani** [comment]
> [JuliaGizmos/WebIO.jl#236 (comment)](https://github.com/JuliaGizmos/WebIO.jl/issues/236#issuecomment-484428662)
> [JuliaGizmos/WebIO.jl#276 (comment)](https://github.com/JuliaGizmos/WebIO.jl/pull/276#issue-271739630)
> 
> It seems like this was a WebIO issue, and once the pull request is merged, it should work.

The pull request was accepted, but no change.
`:8888/nbextensions/webio/main.js?v=20190420155849:1
 WebIO is registering SystemJS window global.
(anonymous) @ :8888/nbextensions/webio/main.js?v=20190420155849:1
main.min.js:24062 Loading extension: webio/main
(unknown) WebIO detected Jupyter notebook environment.
(unknown) Jupyter WebIO nbextension detected; not loading ad-hoc.
(unknown) Jupyter WebIO extension detected, not mounting.`

**Comment by sglyon** [comment]
Thanks for following up here. I'm surprised it isn't working and unfortunately will have to defer to the WebIO experts to get a fix.

**Comment by DhruvaSambrani** [comment]
https://github.com/sglyon/PlotlyJS.jl/issues/278#issuecomment-497939618

**Comment by DhruvaSambrani** [comment]
https://github.com/sglyon/PlotlyJS.jl/issues/278#issuecomment-499970113

**Comment by ghuba** [comment]
Has this been fixed? #278 has been closed after being fixed.

**Comment by lwabeke** [comment]
This now works for me in Julia notebook, both through PlotlyJS directly and using Plots as front-end with versions:
 Julia Version 1.1.1
  [ad839575] Blink v0.10.1
  [f0f68f2c] PlotlyJS v0.12.5
  [91a5bcdd] Plots v0.25.2
  [0f1e0344] WebIO v0.8.6

Although I still get
`Warning: Please upgrade Blink for a smoother integration with WebIO.`

**Comment by sglyon** [comment]
Thank you @lwabeke for reporting back

**Comment by lwabeke** [comment]
No wait, it seems it doesn't work from Plots front-end, although I could have sworn it worked earlier.

When using Plots front-end, I'm getting Console logs below, but with WebIO error message displayed instead of plot:

```[Log] Kernel: kernel_connected (8a56916c-4961-4e2c-b60e-fd0cb56da199) (main.min.js, line 36979)
[Log] Kernel: kernel_starting (8a56916c-4961-4e2c-b60e-fd0cb56da199) (main.min.js, line 36979)
[Log] Kernel: kernel_ready (8a56916c-4961-4e2c-b60e-fd0cb56da199) (main.min.js, line 36979)
[Log] Kernel: kernel_ready (8a56916c-4961-4e2c-b60e-fd0cb56da199) (main.min.js, line 36979)
[Log] WebIO detected Jupyter notebook environment. (testingPlots.ipynb, line 15)
[Log] Jupyter WebIO nbextension detected; not loading ad-hoc. (testingPlots.ipynb, line 24)
[Log] Jupyter WebIO extension detected, not mounting. (testingPlots.ipynb, line 3) 
```

When using PlotlyJS, I'm getting Console logs below and see plot:
```[Log] Kernel: kernel_connected (4633f6c1-5fa6-46b7-b6de-e83b22435fef) (main.min.js, line 36979)
[Log] Kernel: kernel_starting (4633f6c1-5fa6-46b7-b6de-e83b22435fef) (main.min.js, line 36979)
[Log] Kernel: kernel_ready (4633f6c1-5fa6-46b7-b6de-e83b22435fef) (main.min.js, line 36979)
[Log] Kernel: kernel_ready (4633f6c1-5fa6-46b7-b6de-e83b22435fef) (main.min.js, line 36979)
[Log] WebIO detected Jupyter notebook environment. (testingPlotlyJS.ipynb, line 15)
[Log] Jupyter WebIO nbextension detected; not loading ad-hoc. (testingPlotlyJS.ipynb, line 24)
[Warning] Setting new WebIO window global. (main.js, line 1)
```

It looks like using PlotlyJS directly gives the Warning, but still works, while the Plots route goes into the not mounting state. Any idea why they are loading WebIO differently?
