### ISSUE TITLE
index.js and display.jl out of sync

### ISSUE THREAD

**Issue by Rajczyk** [sglyon/PlotlyJS.jl#261]
I was wondering why the relayout event stream wasn't working. I finally tracked it down to the following commit and the changes that need to happen to fix the problem. 

This line of code was changed in commit https://github.com/sglyon/PlotlyJS.jl/commit/c54b847d36010621fcedf352d5eaea5d1c6ffb5a

https://github.com/sglyon/PlotlyJS.jl/blob/17b5821232d7dd4561ea2b139024fbfce81884e2/assets/index.js#L4

The following file needs the lines changing to reflect the above update:

https://github.com/sglyon/PlotlyJS.jl/blob/17b5821232d7dd4561ea2b139024fbfce81884e2/src/display.jl#L101

https://github.com/sglyon/PlotlyJS.jl/blob/17b5821232d7dd4561ea2b139024fbfce81884e2/src/display.jl#L110

https://github.com/sglyon/PlotlyJS.jl/blob/17b5821232d7dd4561ea2b139024fbfce81884e2/src/display.jl#L119

https://github.com/sglyon/PlotlyJS.jl/blob/17b5821232d7dd4561ea2b139024fbfce81884e2/src/display.jl#L126

Thanks

**Comment by sglyon** [comment]
Thank you for tracking this down for us! 

Would you be wiling to open a pull request that implements the specified change?

That would be very helpful!

**Comment by sglyon** [comment]
Thanks @Rajczyk turns out I've had a fix on my local branch for months :face_palm:

I've merged the fix into master and will do a release
