### ISSUE TITLE
Selecting points no longer works

### ISSUE THREAD

**Issue by cstjean** [sglyon/PlotlyJS.jl#262]
On Julia 1.0.3, IJulia v1.15.2, WebIO v0.4.2, PlotlyJS 0.12.2, selecting points no longer works. I'm not 100% sure, but I believe that this used to work in IJulia:

```julia
using PlotlyJS, WebIO
sc = PlotlyJS.scatter(x=[1,2], y=[2,3])
wpl = PlotlyJS.Plot(sc)
sp = PlotlyJS.SyncPlot(wpl)
on(sp["selected"]) do d
    println("point was selected")
end
sp
```

I've tried it on `0.11.2`, and it doesn't work there either. However, `sp["hover"]` works fine. Can anyone reproduce?

**Comment by sglyon** [comment]
Thanks @cstjean I believe this is the same issue as in #261 

I'll see if I can fix it up real quick

**Comment by sglyon** [comment]
Turns out I've had a fix on my local branch for months :face_palm:
