### ISSUE TITLE
Missing support

### ISSUE THREAD

**Issue by cstjean** [sglyon/PlotlyJS.jl#265]
```julia
using PlotlyJS
using PlotlyJS: SyncPlot

SyncPlot(Plot(scattergl(x=[1,2,3], y=[1,missing, 3], mode=:markers)))
```

yields `Cannot serialize type Missing`. I think it would be OK to convert them to `NaN`? That's what `Plots.jl` does IIRC.

**Comment by sglyon** [comment]
Yeah I think that makes sense to me.

What do you think the right approach to that would be? Right now we lean on how JSON.jl wants to serialize things and define a few methods for JSON.lower [here](https://github.com/sglyon/PlotlyBase.jl/blob/7f42d0dab0cc1b419c2d6c88dbcf39ca6b80e4c5/src/json.jl).

I don't think we should be type pirates and define `JSON.lower(::Missing) = NaN`, but as of right now we don't have a layer in PlotlyJS.jl to intercept something like that

**Comment by cstjean** [comment]
@TotalVerb  We'd like to serialize (write) `missing` as `null`, with JSON.jl. I saw your [big PR](https://github.com/JuliaIO/JSON.jl/pull/162), but it doesn't seem to be documented anywhere. What would be the solution for us? I'm a bit confused whether we should implement a Writer, a Context, or a Serialization.

**Comment by TotalVerb** [comment]
JSON.jl already serializes `Missing` as `null`: https://github.com/JuliaIO/JSON.jl/blob/master/src/Writer.jl#L266

It's possible this has not been tagged. I'll check this.

**Comment by TotalVerb** [comment]
I believe the issue is that one of the JSON.lower overrides is calling JSON.lower before returning the result, which is not the intended usage. Please see #266 for a solution.

**Comment by sglyon** [comment]
Thanks @TotalVerb!

@cstjean  I just tried your example with the latest master of PlotlyJS.jl (doesn't include #266) and the code snippet you posted above and it works for me without any modification needed...

What version of JSON.jl and julia do you have? What about your OS (though I can't imagine why that would matter for this issue)?

**Comment by TotalVerb** [comment]
Right, #266 will have no effect if `(::SyncPlot).plot` is never `Missing` and is always a type that this package is aware has already defined `lower`. Nevertheless, the recursive `lower` call is not needed; the documentation for JSON is actively misleading here (I regret that it was written when we had a different design philosophy in mind when the feature was first implemented.)

**Comment by cstjean** [comment]
I can't check right now, but I assume that I just had a lower JSON version installed because of some upper-bound somewhere. Thank you for your help both!

**Comment by sglyon** [comment]
ok sounds good, if you check and it it still an issue please reopen.

Thanks
