### ISSUE TITLE
Hook into plotly events

### ISSUE THREAD

**Issue by sglyon** [sglyon/PlotlyJS.jl#27]
This is definitely possible.

We need to decide on an API.

It _might_ require changes to blink to pass data back and forth for a callback

**Comment by EricForgy** [comment]
Hi @spencerlyon2 My initial thought (without having looked at Plotly events so I may totally off) is this may also be possible with [Pages.jl](https://github.com/EricForgy/Pages.jl) :)

**Comment by spencerlyon2** [comment]
Nice, thanks for the heads up. I won’t have time to get around to this in the foreseeable future, but it’s great to have a reference




// Spencer

On May 11, 2016 at 3:52:57 AM, Eric Forgy (notifications@github.com) wrote:

Hi @spencerlyon2 My initial thought (without having looked at Plotly events so I may totally off) is this may also be possible with Pages.jl :)

**Comment by cstjean** [comment]
Hi, I'd like to use Interact.jl and Plotlyjs to interactively tag certain points (as good/bad). AFAICT, to get the selected points, [I need events](https://plot.ly/r/shiny-coupled-events/)

> Plotly supports two separate click events that can be used to read user inputs using the event_data() function.
>
>   - plotly_selected can be used to return information about data points inside a selection box (box or lasso)
>   - plotly_click can be used to return information about a single data point

Right? Any pointers on where to start working on this? I suppose I could look at how the Python/R Plotly front-ends handle it?

**Comment by sglyon** [comment]
This is actually implemented in https://github.com/sglyon/PlotlyWebIO.jl, which will hopefully become the new "display integration" part of the plotly Julia scene once WebIO.jl is officially released.... so stay tuned!

I think @shashi has the best idea of when that release might happen.

**Comment by cstjean** [comment]
WebIO was released, is there anything I can do to help move PlotlyWebIO forward? It will be a major win for our work!

**Comment by sglyon** [comment]
Sure! Any help would be great.

I think it is pretty much ready as far as features go, but last time I tried (release 0.1.0 of WebIO) things weren't quite stable enough to replace the code here. Now we are on version 0.1.4 of WebIO so it is totally possible that things have stabilized and will "just work".

If you want to grab the latest release of WebIO and the latest master version of PlotlyWebIO and test things out/report any issues that would be great. 

I don't have a lot of time right now for experimenting/debugging, but if someone else were to pitch in on the experimenting/stress-testing side that would be really helpful in getting things moving forward

**Comment by sglyon** [comment]
Now included!

For now, please use the master branch

```julia
] # enter pkg mode
(v1.0) pkg> checkout PlotlyJS
```

If you want save figures you can do

```
] # enter package mode
(v1.0) pkg> add https://github.com/sglyon/ORCA.jl.git#master
```

If this doesn't resolve your issue here, please reopen the issue and leave a comment describing what went wrong
