### ISSUE TITLE
Julia : ERROR: KeyError: key "set_facecolor" not found

### ISSUE THREAD

**Issue by iamsuddhasattwa** [sglyon/PlotlyJS.jl#270]
I am having trouble running the most basic plotting commands in Julia

julia> using Plots

julia> x=rand(100);

julia> plot(x)
WARNING: No strict ticks found
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: KeyError: key "set_facecolor" not found

**Comment by sglyon** [comment]
Sorry, but this is an issue with the Plots package. 

Please post the issue over there

https://github.com/JuliaPlots/Plots.jl

**Comment by iamsuddhasattwa** [comment]
Thank you for your response. I will do that.
- - -
Shuddho,
Suddhasattwa Das
