### ISSUE TITLE
Subplot layout editing issues

### ISSUE THREAD

**Issue by ezgikurt** [sglyon/PlotlyJS.jl#277]
Perhaps this is redundant as it may be stemming from issues similar to #118 #114 but I wanted to mention it in case it is not. When I create a subplot and then try to edit it using the functionality outlined [in docs](http://spencerlyon.com/PlotlyJS.jl/examples/subplots/), this does not work. It used to work on Julia 0.6.4 (and still works on that version).

simple example
```
a1 = plot(1:10)
b1 = plot(10:-1:1)
p = [a1;b1]
p.plot.layout["showlegend"] =false;
```
still shows the legend.

Using Julia v1.1 on Windows 64 & PlotlyJS v0.12.3

**Comment by sglyon** [comment]
Was the plot displayed after running the line `p = [a1; b1]`?

**Comment by ezgikurt** [comment]
yes it displays without any issues. 

> Was the plot displayed after running the line `p = [a1; b1]`?

**Comment by ezgikurt** [comment]
hmm this seems to be a pure display issue, as `showlegend = false` works when I save it into a pdf.

**Comment by sglyon** [comment]
Yes the problem here is that changing an attribute on the Julia object does not also change a previously displayed figure. 

You have two options 

1. Use the `relayout!` function 
2. Suppress the display until after you make the change.

**Comment by ezgikurt** [comment]
Thanks @sglyon 
just a note, relayout! works but option 2 does not, even when I suppress a1, b1 & p.
