### ISSUE TITLE
How to combine heatmap and scatter?

### ISSUE THREAD

**Issue by liuzhaochen** [sglyon/PlotlyJS.jl#280]
I am trying to scatter some points on my heatmap graph. But I  didn't find the way to do it. When I do something like:
`
plot(heatmap(x,y,z),scatter(x,y))
`
the result is  just stacking two graphs together.
How can I plot two graphs in one plots??
Thanks.

**Comment by sglyon** [comment]
Try putting the two traces (plotly terms the output of scatter, heatmap, and friends as traces) inside square brackets to call plot with a single array of traces. Sorry, on phone so am not going to attempt to type out an example

**Comment by liuzhaochen** [comment]
> Try putting the two traces (plotly terms the output of scatter, heatmap, and friends as traces) inside square brackets to call plot with a single array of traces. Sorry, on phone so am not going to attempt to type out an example

Thanks for your answer .I have solved this problem.
