### ISSUE TITLE
Plots on a remote jupyter notebook

### ISSUE THREAD

**Issue by kleskjr** [sglyon/PlotlyJS.jl#291]
I had some troubles setting up a jupyter notebook on a remote instance. 
The notebook consists of the following code:

```
using PlotlyJS
plot([1,2,3])
```

and it executes quetly without generating plot or throwing any error. On the server side, the jupyter notebook shows the following error:

```
[W 09:14:39.034 NotebookApp] 404 GET /assetserver/e8a72785a3a25337443015cbeabb4ba0c89acf03-plotly-latest.min.js (<client_ip>) 1.62ms referer=https://jupyter.xyz:9999/notebooks/dev/Untitled.ipynb
[W 09:14:39.084 NotebookApp] 404 GET /assetserver/e450be4f6fe6f88ccac9afc92f9b6a033701b010-plotly_webio.bundle.js (<client_ip>) 1.45ms referer=https://jupyter.xyz:9999/notebooks/dev/Untitled.ipynb
```

where <client_ip> is the local ip, from which I open the browser. Looks like plotly/webIO couldn't communicate with the browser. I was wandering where this problem comes from. Interestingly, when using the Plots interface of plotlyjs, plotting works! 

```

julia> versioninfo()
Julia Version 1.0.5
Commit 3af96bcefc (2019-09-09 19:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```
```

julia> Pkg.status()
    Status `~/.julia/environments/v1.0/Project.toml`
  [864edb3b] DataStructures v0.17.0
  [587475ba] Flux v0.9.0
  [7073ff75] IJulia v1.20.0
  [6f286f6a] MultivariateStats v0.7.0
  [f0f68f2c] PlotlyJS v0.12.5
  [91a5bcdd] Plots v0.26.3
  [2913bbd2] StatsBase v0.32.0
  [0f1e0344] WebIO v0.8.11
```

Similar results were achieved with Julia 1.2.

**Comment by sglyon** [comment]
@shashi and @travigd do either of you know of any installation issues of WebIO on a non-root-access jupyter server?

**Comment by travigd** [comment]
No there shouldn't be any issues.

It looks like @kleskjr's issue is that the WebIO's asset server isn't working.

This line should appear towards the bottom of `~/.jupyter/jupyter_notebook_config.py`:
```py
import os, sys, warnings
webio_deps_dir = "/Users/travigd/.julia/dev/WebIO/deps"
if os.path.isfile(os.path.join(webio_deps_dir, "jlstaticserve.py")):
    sys.path.append(webio_deps_dir)
else:
    warning_msg = (
        'Directory %s could not be found; WebIO.jl will not work as expected. '
        + 'Make sure WebIO.jl is installed correctly (try running '
        + 'Pkg.add("WebIO") and Pkg.build("WebIO") from the Julia console to '
        + 'make sure it is).'
    ) % webio_deps_dir
    warnings.warn(warning_msg)
```

and this should be in `~/.jupyter/jupyter_notebook_config.json`:
```json
{
  "NotebookApp": {
    "nbserver_extensions": {
      "jlstaticserve": true
    }
  }
}
```

I think older versions of Jupyter won't attempt to reconcile the two files and only load the JSON - but if that's the case, then you should get import errors.

**Comment by kleskjr** [comment]
thanks a lot @travigd, @sglyon! Indeed, it was misconfigured file.

**Comment by sglyon** [comment]
Thanks @travigd !

**Comment by kleskjr** [comment]
The files were properly configured. It was my fault that after I did backup and did not correctly restore the configuration to the new files. Thanks @travigd.
