### ISSUE TITLE
color scale question

### ISSUE THREAD

**Issue by IgorDouven** [sglyon/PlotlyJS.jl#292]
I'm not sure this is the right place to ask this question. If not, please let me know where I should post this. In any case, I have a line plot and would like the lines to be differently colored, but their order should respect some color scale. For instance, in
```
data = rand(10, 10)
Plot(x=1:size(data, 2), data, showlegend=false)
```
I might want to use the Viridis scale, and have the line that starts at the top appear in a darker green than the line that starts below it, have the latter appear in a darker green than the line that starts below *it*, and so on. Can this be done? Hints very much appreciated.

**Comment by sglyon** [comment]
You can do this using the ColorScales package and by setting `layout.colorway` when making the plot. 

Here's an example:

```julia
using ColorSchemes
using PlotlyJS

plot(
    rand(20) .+ reshape(1:10, 1, :), 
    Layout(colorway=ColorSchemes.viridis.colors[1:20:end]), 
    line_width=5
)
```


Notice that I skip 20 colors at a time in the viridis color scale. There are 256 colors in `ColorSchemes.viridis.colors` and successive ones are very similar and hard to distinguish. Using every 20th let me use up through 200 and have them nicely distinguishable for 10 lines.


Note that you you can make this a default by setting the default style:

```julia
using ColorSchemes
using PlotlyJS

viridis_style = Style(layout=Layout(colorway=ColorSchemes.viridis.colors[1:20:end]))
use_style!(viridis_style)
plot(rand(20) .+ reshape(1:10, 1, :))
```

**Comment by IgorDouven** [comment]
Many thanks, that's very helpful!

Op do 3 okt. 2019 om 15:40 schreef Spencer Lyon <notifications@github.com>:
