### ISSUE TITLE
"options" keyword does not affect figure

### ISSUE THREAD

**Issue by sindresops** [sglyon/PlotlyJS.jl#300]
Passing options has no effect on how the plot is displayed. 

`p = plot([scatter([0, 1]), options=Dict(:showLogo => false))`

should remove the logo button in the top-right modebar. But it is still there. Same goes for other settings. The option does not seem to be passed to the JSON object, evidenced by that

`JSON.print(p,2)`

yields

`{
  "layout": {
    "margin": {
      "l": 50,
      "b": 50,
      "r": 50,
      "t": 60
    }
  },
  "data": [
    {
      "y": [
        0,
        1
      ],
      "type": "scatter",
      "x": [
        1,
        2
      ]
    }
  ]
}`
**Version info**

Please provide the following:

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

[336ed68f] CSV v0.5.14
  [a2e0e22d] CalculusWithJulia v0.0.1
  [5ae59095] Colors v0.9.6
  [a93c6f00] DataFrames v0.19.4
  [5789e2e9] FileIO v1.0.7
  [38e38edf] GLM v1.3.3
  [c91e804a] Gadfly v1.0.1
  [fd0ad045] GeometricalPredicates v0.3.0
  [4c0ca9eb] Gtk v0.18.0
  [7073ff75] IJulia v1.20.1
  [6218d12a] ImageMagick v0.7.5
  [916415d5] Images v0.18.0
  [6deec6e2] IndexedTables v0.12.4
  [c601a237] Interact v0.10.3
  [682c06a0] JSON v0.21.0
  [fc18253b] LazyJSON v0.1.1
  [a90b1aa1] LibGEOS v0.5.0
  [ae8d54c2] Luxor v1.7.0
  [ee78f7c6] Makie v0.9.5
  [47be7bcc] ORCA v0.3.0
  [58dd65bb] Plotly v0.2.0
  [91a5bcdd] Plots v0.27.0
  [f27b6e38] Polynomials v0.5.3
  [d330b81b] PyPlot v2.8.2
  [b0e4dd01] RollingFunctions v0.6.2
  [f3b207a7] StatsPlots v0.12.0
  [24249f21] SymPy v1.0.7
  [d6d074c3] VideoIO v0.6.10
  [0f1e0344] WebIO v0.8.11
  [fdbf4ff8] XLSX v0.5.8

**Comment by sglyon** [comment]
Hi @sindresops I think the issue here is that you aren't using a proper plotly.js configuration option.

See here for documentation: https://plot.ly/javascript/configuration-options/

I tried `p = plot(rand(10, 10), options=Dict(:editable => true))` and it let me edit titles/axis labels on the chart itself.

**Comment by sindresops** [comment]
Hi @sglyon 

the "editable" option also does nothing on my end. Also tried on a colleague's workstation with the same result. The plot displays, is interactive, but there are no options to edit axes or labels (neither in JupyterLab nor saved as HTML). 

![image](https://user-images.githubusercontent.com/29738855/69176488-16e46e80-0b06-11ea-93ff-b91d8990e29f.png)

**Comment by sglyon** [comment]
yikes ok....

the json won't show it because that is only the json for the chart.

We call into the Plotly.newPlot javascript function which accepts a div, data, layout, and options. When you call `json(p)` it will only show you `data` and `layout`.

This was an intentional design decision because I felt the options were more part of viewing the chart in a specific context and not part of the chart specification itself.

**Comment by sindresops** [comment]
Okay, that sounds reasonable I suppose

Are you aware of any workarounds to our issue? We can of course assist in diagnosing it.

**Comment by sglyon** [comment]
Could you open the javascript console of your browser before creating the plot and then report back anything that appears after plotting?

**Comment by sindresops** [comment]
`[Violation] Forced reflow while executing JavaScript took 40ms
codemirror.js:3905 [Violation] 'mousedown' handler took 181ms
codemirror.js:517 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
on @ codemirror.js:517
registerEventHandlers @ codemirror.js:7939
CodeMirror @ codemirror.js:7869
CodeMirror @ codemirror.js:7828
createEditor @ editor.js:928
CodeMirrorEditor @ editor.js:107
CodeMirrorEditorFactory.newInlineEditor @ factory.js:17
CodeEditorWrapper @ widget.js:30
onActiveCellChanged @ notebooktools.js:325
processMessage @ notebooktools.js:205
invokeHandler @ index.js:436
sendMessage @ index.js:172
(anonymous) @ notebooktools.js:136
each @ iter.js:155
_onActiveCellChanged @ notebooktools.js:135
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_onActiveCellChanged @ tracker.js:79
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set activeCellIndex @ widget.js:689
runAndAdvance @ actions.js:371
execute @ index.js:688
push.5TpB.CommandRegistry.execute @ index.js:351
push.5TpB.CommandRegistry._executeKeyBinding @ index.js:507
push.5TpB.CommandRegistry.processKeydownEvent @ index.js:446
push.2R+v.Application.evtKeydown @ index.js:340
push.2R+v.Application.handleEvent @ index.js:296
codemirror.js:517 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
on @ codemirror.js:517
registerEventHandlers @ codemirror.js:7952
CodeMirror @ codemirror.js:7869
CodeMirror @ codemirror.js:7828
createEditor @ editor.js:928
CodeMirrorEditor @ editor.js:107
CodeMirrorEditorFactory.newInlineEditor @ factory.js:17
CodeEditorWrapper @ widget.js:30
onActiveCellChanged @ notebooktools.js:325
processMessage @ notebooktools.js:205
invokeHandler @ index.js:436
sendMessage @ index.js:172
(anonymous) @ notebooktools.js:136
each @ iter.js:155
_onActiveCellChanged @ notebooktools.js:135
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_onActiveCellChanged @ tracker.js:79
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set activeCellIndex @ widget.js:689
runAndAdvance @ actions.js:371
execute @ index.js:688
push.5TpB.CommandRegistry.execute @ index.js:351
push.5TpB.CommandRegistry._executeKeyBinding @ index.js:507
push.5TpB.CommandRegistry.processKeydownEvent @ index.js:446
push.2R+v.Application.evtKeydown @ index.js:340
push.2R+v.Application.handleEvent @ index.js:296
codemirror.js:517 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
on @ codemirror.js:517
registerEventHandlers @ codemirror.js:7985
CodeMirror @ codemirror.js:7869
CodeMirror @ codemirror.js:7828
createEditor @ editor.js:928
CodeMirrorEditor @ editor.js:107
CodeMirrorEditorFactory.newInlineEditor @ factory.js:17
CodeEditorWrapper @ widget.js:30
onActiveCellChanged @ notebooktools.js:325
processMessage @ notebooktools.js:205
invokeHandler @ index.js:436
sendMessage @ index.js:172
(anonymous) @ notebooktools.js:136
each @ iter.js:155
_onActiveCellChanged @ notebooktools.js:135
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_onActiveCellChanged @ tracker.js:79
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set activeCellIndex @ widget.js:689
runAndAdvance @ actions.js:371
execute @ index.js:688
push.5TpB.CommandRegistry.execute @ index.js:351
push.5TpB.CommandRegistry._executeKeyBinding @ index.js:507
push.5TpB.CommandRegistry.processKeydownEvent @ index.js:446
push.2R+v.Application.evtKeydown @ index.js:340
push.2R+v.Application.handleEvent @ index.js:296
plotly.js:137247 [Violation] 'setTimeout' handler took 206ms
[Violation] Forced reflow while executing JavaScript took 44ms`

**Comment by sglyon** [comment]
Hmm, nothing in there looks off to me. 

I can't reproduce locally in any of jupyterlab, jupyter notebook, or blink based standalone display:

![Screenshot from 2019-11-21 11-02-40](https://user-images.githubusercontent.com/1001948/69354699-882f3900-0c4e-11ea-87a7-015010927a25.png)


![Screenshot from 2019-11-21 10-59-33](https://user-images.githubusercontent.com/1001948/69354704-8a919300-0c4e-11ea-886a-983ebd2ec4b5.png)

**Comment by sindresops** [comment]
Hi @sglyon,

Thanks for trying. I had a go in Jupyter Notebook, and the titles became editable. So I suppose it is a Jupyter Lab issue. Or something to do with @jupyterlab/plotly-extension?

**Comment by sindresops** [comment]
Okay, so apparently in the recent 1.2 update of JupyterLab, support for plotly renreding was included, and the extension deprecated. 

Closing issue as resolved.

Love PlotlyJS.jl btw!

**Comment by sglyon** [comment]
Great! Thanks for reporting back

**Comment by sindresops** [comment]
Quick clarification: How do I pass the display configuration on to the plot saved to file, say HTML?
