### ISSUE TITLE
Usage of API functions, how does they work in Julia 1.2.0?

### ISSUE THREAD

**Issue by crash-crush** [sglyon/PlotlyJS.jl#305]
Hello,

I have tried several Julia Plotting Packages in order to update a heatmap in runtime. Therefore I found these function from the API, but I didn't got them to work to test them out. And furthermore I don't know yet how to see the possible attributes of the functions and in which way I can set them to any value?
[http://spencerlyon.com/PlotlyJS.jl/manipulating_plots/](http://spencerlyon.com/PlotlyJS.jl/manipulating_plots/)
I tried `react!` but probably wrong.

Thanks for help.

**Comment by sglyon** [comment]
Hi @crash-crush thanks for posting.

Could you provide a small code snippet that demonstrates what you've tried. That will give us a starting point to figure out how to help!

**Comment by crash-crush** [comment]
Ok. Thanks for the fast response. Its important for winning people to the julia community :)

Here I go what I have tried and what I have wanted(I think it's clear from the "not- working- code")

```
using PlotlyJS
using Plotly

plot(heatmap(z=rand(100,100)))
Plotly.plot(heatmap(z=rand(100,100)))  
#till here everything wents great just an aspect-ratio of 1 would be wishable.
#then I have tried with some errors occuring the react! function

react!(plot(heatmap(z=rand(100,100)))) #error 
Plotly.react!(heatmap(z=rand(100,100))) #error 
```

Furthermore I wanted to put these into a for loop to get a live view from processing for approximately 1*10^6 to 10^9 steps

Thanks in advance.

**Comment by sglyon** [comment]
This should work...


```julia
using PlotlyJS

p = plot(heatmap(z=rand(100,100)))
restyle!(p, z=[rand(100, 100)])
```

The `react!` function is used when you are changing both the traces and layout. When you only want to change one or more traces, the `restyle!` function is a bit easier to work with.

Note that you need to wrap the new data in a container like an array or a tuple. This is because `restyle!` is meant to be able to change the data for more than one trace. To distinguish which traces gets which new data, plotly will index into the container.

**Comment by crash-crush** [comment]
Thank thats works, even in a for loop but pretty slow.
How can I in addition to this ,because it would be the same type of structure manipulating, get an aspect ratio of 1, also quadratic matrix element representation?
Is there something like annotate structure attributes like
`p.aspect_ratio=1`

and how can I list the possible attributes?

**Comment by sglyon** [comment]
I'm not sure how to fix the aspect ratio... perhaps the width and height in the layout?

You can see a full list of everything configurable here: https://plot.ly/javascript/reference/

I'm going to close the issue as I think we've resolved the original problem
