### ISSUE TITLE
Neither showEditInChartStudio nor showSendToCloud configurations have any effect

### ISSUE THREAD

**Issue by PetrKryslUCSD** [sglyon/PlotlyJS.jl#313]
My `layout` sets the configuration options so that the Json reads
```
"showEditInChartStudio": true,
    "showSendToCloud": true,
```
The resulting figure does not have the requested button: 
![image](https://user-images.githubusercontent.com/9855832/75404145-8cf33100-58be-11ea-920f-1ce63db2ceb5.png)
Is that something that doesn't work at the moment, or is that a bug?

**Comment by PetrKryslUCSD** [comment]
Sorry, it appears I misunderstood the instructions I found on the web (or they might have been outdated): these configurations need to go into the `options` argument. That works fine.

**Comment by sglyon** [comment]
no problem. Were you able to figure this out?

**Comment by PetrKryslUCSD** [comment]
I did. This works:
```
pl = plot(plots, layout; options=Dict(:showSendToCloud=>true))
display(pl)
```
Thanks.
