### ISSUE TITLE
react! does not update plot

### ISSUE THREAD

**Issue by shashi** [sglyon/PlotlyJS.jl#317]
**Describe the bug**
`react!` with data and layout does not update the plot.
Cell 1:
```julia
p = Plot(rand(10), rand(10), mode="markers", marker_size=8)
s= PlotlyJS.SyncPlot(p)
```
This displays the plot
```julia
p1 = Plot(rand(10), rand(10), mode="markers", marker_size=8)
react!(s, p1.data, p1.layout)
```
doesn't update it...

Am I using it wrong?

**Version info**
Please provide the following:

1. output of julia command `versioninfo()`

```julia
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

2. Output running the following in Julia 0.7 or greater: `using Pkg; pkg"status"` (if you are on Julia 0.6 or earlier run `Pkg.status()`)
```
Status `./Project.toml`
  [336ed68f] CSV v0.6.0
  [9024f26f] Dashboards v0.2.8
  [a93c6f00] DataFrames v0.20.2
  [cd3eb016] HTTP v0.8.13
  [510215fc] Observables v0.2.3
  [f0f68f2c] PlotlyJS v0.13.1 [`~/.julia/dev/PlotlyJS`]
  [91a5bcdd] Plots v0.29.9
  [ce6b1742] RDatasets v0.6.7
  [0f1e0344] WebIO v0.8.13
```

**Comment by sglyon** [comment]
Hey @shashi the `Plot` function (with capital `P`) creates the Julia in-memory version of the plot. It doesn't know about any attached displays.

Can you retry using the `plot` function (lowercase `p`) and see if that fixes the issue?

**Comment by shashi** [comment]
Actually the code in the OP worked for me, sorry for the noise!

I actually intended to use `Plot` because SyncPlot takes a `Plot`, and `Plot` is a convenient way to construct the arguments to `react!`

**Comment by sglyon** [comment]
oh cool, no problem.
