### ISSUE TITLE
Problem for mesh3d intensity

### ISSUE THREAD

**Issue by ZenanH** [sglyon/PlotlyJS.jl#324]
I'm using `PlotlyJS.jl` to draw my model and I chose to use `mesh3d()` for my task. The model is composed of tetrahedral elements, so `i_1`, `j_1`, `k_1` represent the serial number of one of the triangular faces. The code reads as follows:

```julia
using PlotlyJS

trace = mesh3d(x = [...],
               y = [...],
               z = [...],
               i = [i_1, i_2, ...],
               j = [j_1, i_2, ...],
               k = [k_1, k_2, ...])

layout = Layout(...)

plot(trace, layout)
```

![1](https://user-images.githubusercontent.com/19581645/81492528-22ea0580-92cb-11ea-83b9-54a65c8b6fba.png)

I'm not sure if there's a problem with the red area being displayed in the picture. After that, I added something about intensity:

```julia
using PlotlyJS

trace = mesh3d(x = [...],
               y = [...],
               z = [...],
               i = [i_1, i_2, ...],
               j = [j_1, i_2, ...],
               k = [k_1, k_2, ...],
               intensity = abs.(result[:,3]),
               intensitymode = "vertex",
               colorscale = "RdBu")

layout = Layout(...)

plot(trace, layout)
```

![2](https://user-images.githubusercontent.com/19581645/81492592-99870300-92cb-11ea-93b3-c345b80d305a.png)

The same problem can be seen in the red area. It may change with perspective:

![1](https://user-images.githubusercontent.com/19581645/81492706-b2dc7f00-92cc-11ea-823e-4ae5c7da5173.gif)

But I think maybe it should be like the picture below:

![3](https://user-images.githubusercontent.com/19581645/81492762-1e265100-92cd-11ea-8e04-feec978eec0a.png)

Is there anything I can do? I'm not sure what's wrong. 😅

**Comment by sglyon** [comment]
Hi @ZenanH thanks for posting.

I'll be honest here -- I am not an expert in 3d rendering/plotting. I believe I've never even used the mesh3d method myself!

Sorry about that!

You may have better luck on the plotly discussion forum: https://community.plotly.com/

I'm going to close here as I don't believe it is an issue with this library. If I turn out to be wrong about that and there is something to fix here please feel free to re-open.
