### ISSUE TITLE
How to customize download plot options?

### ISSUE THREAD

**Issue by ZenanH** [sglyon/PlotlyJS.jl#326]
In the [documentation](https://plotly.com/javascript/configuration-options/#customize-download-plot-options) for the `Plotly Javascript`, I noticed that the options for downloading plot can be changed.  I would like to do a similar setup in `PlotlyJS.jl` to download plot directly in `SVG` format, what should I do? 😅
![image](https://user-images.githubusercontent.com/19581645/82034667-130a6100-96d1-11ea-8367-4cd4ce834b4b.png)

**Comment by disberd** [comment]
Hi @ZenanH,

You can use the `options` keyword argument to the PlotlyJS.plot function as explained at the bottom of [this](http://spencerlyon.com/PlotlyJS.jl/syncplots/) page of the documentation.

You can reproduce the linked example from the plotlyjs documentation by adapting to PlotlyJS.jl syntax with the following code:

```julia
using PlotlyJS

trace1 = scatter(
    x=[0, 1, 2, 3, 4, 5, 6],
    y= [1, 9, 4, 7, 5, 2, 4],
    mode= "markers",
    marker_size = [20, 40, 25, 10, 60, 90, 30]
)

layout = Layout(;
    title= "Download Chart as SVG instead of PNG",
    showlegend= false
);

config = Dict(
  :toImageButtonOptions => Dict(
    :format => "svg", # one of png, svg, jpeg, webp
    :filename => "custom_image",
    :height => 500,
    :width => 700,
    :scale => 1 # Multiply title/legend/axis/canvas sizes by this factor
  )
);
plot(trace1,layout;options=config)
```

**Comment by ZenanH** [comment]
Thanks, it worked! I hadn't noticed it in the documentation before.😅

**Comment by sglyon** [comment]
thank you @disberd !!

Sorry for slow response @ZenanH

**Comment by jwintersinger** [comment]
Hello! Unfortunately, the code above no longer works for me.  If I call `savefig(plot(trace1, layout, options=config), "out.html")`, the image Plotly saves for me when I click the "download image" button is still a PNG at the default size. There's no record of any of the options I specified in `plot_json` within `out.html`. Is there perhaps an easy fix, given that PlotlyJS.jl doesn't seem to recognize `options` any longer?

Thanks!

**Comment by empet** [comment]
The following lines of code  do save a html version of the plot:

```
pl = plot(trace, layout, style=plotlyju) #plotlyju.jl is my style file
savefig(pl, "surf.html")
```
If you are working with the default style, then remove the  style setting from the plot definition.

**Comment by jwintersinger** [comment]
Thanks, @empet! Unfortunately, that part was already working for me -- I have no problem writing the HTML file and having the plot render in my browser. My issue is specifically with being able to specify the format and dimensions of the image that the browser will save when I click Plotly's "download image" button.

In fact, in the PlotlyJS.jl source tree, the minimal example given in `PlotlyJS.jl/docs/src/syncplots.md` doesn't work for me, so I'll open a new issue.
