### ISSUE TITLE
Add options for savefig

### ISSUE THREAD

**Issue by sglyon** [sglyon/PlotlyJS.jl#4]
Minimum options needed:
- width 
- height
- dpi

The width/height options would preferably accept measures like `height=4inch, width=8inch`

This might be relevant: http://stackoverflow.com/a/26047748/1742701

**Comment by asbisen** [comment]
Can we also add another option to `savefig` when saving output to `html`. Currently the html references local copy of `plotly.js`. Either we can embed the `plotly.js` inside the `html` such that the file is portable or we can add an option to use the CDN URI. Something like..

```julia
savefig(p, "plot.html", js=("remote", "local", "embed")) 
```

**Comment by spencerlyon2** [comment]
Excellent idea. I'd be happy to accept a pull request if you feel up for it.

To me it sounds like a keyword argument with type `Symbol` would work well.
What do you think?

// Spencer

**Comment by asbisen** [comment]
Done you can review it here https://github.com/asbisen/PlotlyJS.jl

usage would look like:

`savefig(p, "testr.html", js=:local)`
- `:local` would be default or could be provided explicitly
- `:remote` would reference the CDN
- `:embed` would embed adding ~1.7MB to the file
