### ISSUE TITLE
line labels and legends for subplots collect next to the first subplot

### ISSUE THREAD

**Issue by jstac** [sglyon/PlotlyJS.jl#59]
See, for example, the 4th figure here:

http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.applications/blob/master/discrete_dp/discrete_dp_solutions_jl.ipynb

(After the statement "We next plot the consumption policies along the value iteration. ")

If you change the backend to `pyplots`, then legends are correct.

**Comment by tbreloff** [comment]
This is somethings that stumped me. I'd love help to figure it out.

**Comment by spencerlyon2** [comment]
I believe, but could be wrong, that plotly figures have one legend per figure. This means that if we have more than one subplot in a figure, we still have only one legend.

Something I've done in a very similar situation is use the legendgroup trace attribute to either group legend entries or group AND combine them.

You can see an example of grouping and combining here: http://nbviewer.jupyter.org/gist/spencerlyon2/46e6df8ad3b84450b8cb#Unemployment-IRF-in-monthly-models

If this seems like a workable solution and you want to be able to produce figures like this let me know and I'll give the code 😄

**Comment by sglyon** [comment]
This is a "feature"/behavior of plotly.js.

There is no support for multiple legends, though it has been requested on the plotly.js repo: https://github.com/plotly/plotly.js/issues/1668

Will close here and if/when that gets resolved things should "just work" here too.
