### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by sglyon** [sglyon/PlotlyJS.jl#61]
This issue here to serve as a public wishlist for things people would like to see in the next release of PlotlyJS.jl. Essentially this is supposed to be a list of all the things you'd like to have/see in your ideal plotting package. This could be new feature suggestions or API wishes or anything else you can think of (though we can't promise everything will be implemented).

I'm going to copy the quantecon team here because we have some plans to push the library forward for QE usage, but contributions from anyone are absolutely welcome!

cc: @jstac, @cc7768, @mmcky, @oyamad, @albep, @vgregory757, @albop, @thomassargent30, @ZacCranko, @szokeb87, @danielcsaba

**Comment by albep** [comment]
Hey @spencerlyon2 this is great, can't wait to see what new features will be suggested and implemented. From the kinds of plots I end up using, I find the only missing piece I'd like in PlotlyJS is LaTeK integration - something you're well aware of. So not much original contribution from me, but this is to say that for my usual plots I'm happy with what PlotlyJS gives

**Comment by cc7768** [comment]
I know some people feel strongly about being able to draw violin plots. If you give me some "marching orders" then I might be able to try and help implement this.

Bonus points if you saw this coming.

**Comment by tbreloff** [comment]
You can already do violin plots through StatPlots.

**Comment by jstac** [comment]
How about adding a simplified syntax for basic plots?  For example, many plotting packages will do what you expect when you enter

 `plot(x, y, color="blue")`

Free disposal applies...

**Comment by oyamad** [comment]
I have never used any plotting package other than PyPlot.jl, so it might have been there already, but I think it would be nice if a histogram can be plotted with one command.

[Here](http://nbviewer.jupyter.org/github/oyamad/stochevolution/blob/master/KMR2x2_example_jl.ipynb) is an example (Cell [8]), where I used `fit` from `StatsBase`. It would be nice if something like `hist(x, 0:N)` plots a histogram without reference to `StatsBase.fit` or anything.

**Comment by asbisen** [comment]
I would like this already excellent library to have the following capabilities, some might exist already that I might have missed. 

- [ ] Documentation improvements (with syntax and examples in docstring) <-- I can help here
- [ ] Resize Plots when window size is changed
- [ ] Linked multi plots
- [ ] Ability to export multiple plots in a single external HTML
- [ ] Display static plots (SVG, PNG) in Jupyter 
- [ ] High Level Charts
    - [ ] Native support for DataFrames
    - [ ] Basic data aggregation capabilities (like `by`, `color`, `size` arguments)
    - [ ] [Violin Plot] (https://stanford.edu/~mwaskom/software/seaborn/examples/simple_violinplots.html)
    - [ ] [Scatter Plot Matrix](https://stanford.edu/~mwaskom/software/seaborn/examples/scatterplot_matrix.html)
    - [ ] Candle Stick
    - [ ] Printing Tables (DataFrames)
    - [ ] [Joint Plot] (https://stanford.edu/~mwaskom/software/seaborn/examples/hexbin_marginals.html)

**Comment by vgregory757** [comment]
Thanks for doing this @spencerlyon2! I haven't used PlotlyJS.jl on its own that much, but I have noticed that the plots don't show up in previews of a Jupyter notebook (like on GitHub). Also, this might be implemented already, but I always like if a plotting package has a way to easily change the aspect ratios of each subplot when you have multiple.

**Comment by spencerlyon2** [comment]
LaTeX support (in all settings except a notebook in Chrome) and plot resizing finished on master branch.

**Comment by spencerlyon2** [comment]
@asbisen can I ask, what are you looking for when you ask to display static plots in Jupyter notebook? 

Right now it _should_ be possible to define a `display_static(::SyncPlot, format::Symbol)` function that uses Electron to produce the desired static image. This would be very helpful for things like pdf export from a notebook.

**Comment by spencerlyon2** [comment]
Also, @asbisen what would you like the multiple export, single html file to look like? Just plots one on top of another? We could potentially add a method `savefig{N}(::NTuple{N,Plot}, filename)` that does just that.

**Comment by asbisen** [comment]
On static plot @spencerlyon2 I think you have defined it accurately. Currently the plots generated are interactive (and they are great for exploratory data analysis), but there is also a need in my view to be able to generate static high quality versions for publishing them or for shared Jupyter notebooks (PDF, SVG or PNG). 


On multiple export I would defer the what to experts here. But I was thinking something along the lines of stacking multiple of these plots in a single HTML (potentially wrapped inside a nice default CSS for visual aesthetics). Sort of like a journal that can capture all the outputs in a shareable html format. This also ties in well with the sub request of `Printing Tables`. 

This might be out of scope for the project... But you did asked for a wish list right? ;-)

**Comment by sglyon** [comment]
Many of these things have been resolved. 

Those that aren't should have their own issues. If you have a favorite item on this list that has not been implemented and you want to vote for its implementation, please open an issue.
