### ISSUE TITLE
savefig hangs if the plot hasn't been displayed for long enough

### ISSUE THREAD

**Issue by tbreloff** [sglyon/PlotlyJS.jl#73]
This happens either if the plot is not displayed, or if the plot is displayed but then savefig is immediately called (presumably the Blink setup is still happening).  This is how I reproduce:

``` julia
julia> using Plots; plotlyjs(); plot(rand(10),show=true); savefig("/tmp/tmp.png")
^CError handling websocket connection:
InterruptException:EOFError: read end of file
 in read at ./iobuffer.jl:88 [inlined]
 in read(::TCPSocket, ::Type{UInt8}) at ./stream.jl:787
 in byteat at /home/tom/.julia/v0.5/JSON/src/Parser.jl:55 [inlined]
 in current at /home/tom/.julia/v0.5/JSON/src/Parser.jl:66 [inlined]
 in chomp_space! at /home/tom/.julia/v0.5/JSON/src/Parser.jl:110 [inlined]
 in parse_value(::JSON.Parser.StreamingParserState{TCPSocket}, ::Type{T}) at /home/tom/.julia/v0.5/JSON/src/Parser.jl:153
 in #parse#2(::Type{Dict{String,Any}}, ::Function, ::TCPSocket) at /home/tom/.julia/v0.5/JSON/src/Parser.jl:392
 in macro expansion at /home/tom/.julia/v0.5/Lazy/src/macros.jl:258 [inlined]
 in macro expansion at /home/tom/.julia/v0.5/Blink/src/AtomShell/process.jl:94 [inlined]
 in (::Blink.AtomShell.##6#7{Blink.AtomShell.Electron})() at ./event.jl:68
```

(the error happens after I control-C... seems like there was an infinite wait on the `read(::TCPSocket, ::Type{UInt8})`

**Comment by spencerlyon2** [comment]
Ultimately this is something that should be resolved in Blink. 

I could think of hacky ways to get it to work here (e.g. don't try to do anything for a certain amount of time after a plot is displayed), but that isn't satisfying.

@MikeInnes any idea how make sure the socket is ready and set up before waiting on it?

**Comment by MikeInnes** [comment]
Take a look for `isactive` or `wait` methods in the Blink source code. Waiting for the page to be loaded may be enough in this case but I'm not sure if you need a way to tell if the page is loading – but we could add something like that.
