### ISSUE TITLE
Plot, plot, [plots] and docs

### ISSUE THREAD

**Issue by amellnik** [sglyon/PlotlyJS.jl#74]
I noticed today that the docs are slightly out of sync with the way the latest tagged version works.  

``` julia
p1 = Plot(scatter(;y=randn(3)))
p2 = Plot(histogram(;x=randn(50), nbinsx=4))
p3 = Plot(scatter(;y=cumsum(randn(12)), name="Random Walk"))
[p1 p2]
```

produces text output, while 

``` julia
p1 = plot(scatter(;y=randn(3)))
p2 = plot(histogram(;x=randn(50), nbinsx=4))
p3 = plot(scatter(;y=cumsum(randn(12)), name="Random Walk"))
[p1 p2]
```

or 

``` julia
p1 = Plot(scatter(;y=randn(3)))
p2 = Plot(histogram(;x=randn(50), nbinsx=4))
p3 = Plot(scatter(;y=cumsum(randn(12)), name="Random Walk"))
plot([p1 p2])
```

displays the plots.  

It might also be worth mentioning how to programatically construct arrays of plots.    For example

``` julia
plots = [
    plot(histogram2d(;x=p[:x], y=p[:y]))
    for p in groupby(df, :category)
]
```

creates a `Array{PlotlyJS.SyncPlot{PlotlyJS.JupyterDisplay},1}` which renders as text, rather than a `PlotlyJS.SyncPlot{PlotlyJS.JupyterDisplay}` (the type of `[p1 p2]`).  However, it can be made to display by calling 

``` julia
vcat(plots...)
```

I can submit a PR to try to clear this up later this week if no one beats me to it.

**Comment by spencerlyon2** [comment]
These are all really good points. Thanks for bringing it up.

I don't have the time to work on it right away, so if you happen to beat me to it by the end of the week that'd be great!

**Comment by spencerlyon2** [comment]
And can you clarify which part of the docs seem to be incorrect.

Given your three examples and description of text vs display I would have guessed exactly what you've reported. Do the docs say something different?

**Comment by amellnik** [comment]
I think the subplots-specific section is correct as written, but the first example I posted is from the [working with plots section](http://spencerlyon.com/PlotlyJS.jl/manipulating_plots/#subplots).  I'm also working to sort out and document the best way of displaying n separate plots in a loop -- I know I had this working at some point and need to find it again.

**Comment by spencerlyon2** [comment]
Ahh I see. I think there we can replace `Plot` with `plot` when building p1-p4 for that section.

Would this not work for displaying in a loop:

```julia
for i in 1:n
    p = plot(...)
    display(p)
end
```

?

**Comment by amellnik** [comment]
Whoops, that definitely works -- I mixed up `display` and `show`!

**Comment by amellnik** [comment]
I think the current version of the docs makes the distinctions nice and clear -- closing.

**Comment by sglyon** [comment]
Thanks for following up!
