### ISSUE TITLE
no show (Windows 7, Julia 0.5, electron)

### ISSUE THREAD

**Issue by PaulSoderlind** [sglyon/PlotlyJS.jl#81]
Hi,
and thanks for the nice package. Seems to work well in Jupyter (Win 7, Julia 0.5), but doing include("test.jl") in the REPL gives a very random experience: most of the time Electron just opens a blank white window. Sometimes the figure shows up. I have so far not observed a pattern in this.

Paul S

**Comment by spencerlyon2** [comment]
I'm sorry you're seeing inconsistency with Electron. I haven't noticed anything similar, but I don't  use Windows. Perhaps it is an issue with Windows + Electron? @MikeInnes does this sound like it might be the problem?

@PaulSoderlind I'm worried there isn't much I can do if there isn't a reproducible way to make the problem happen. If you do figure out a consistent way to trigger the issue please let me know

**Comment by PaulSoderlind** [comment]
Hi,
and thanks for the reply. The problem basically happened almost all the time, but sometimes/somehow didn't. 

Today, Blink was updated to 0.4.3 and I checked out the latest PlotlyJS.jl master (0.5.0+). This changed things. Running a script shows the 2nd plot (and all further plots) in Electron. The first plot is not shown. Still, this is much better than before.

/Paul S

**Comment by spencerlyon2** [comment]
Thanks for the follow up. That is very strange that the first plot doesn't show up.

@MikeInnes is the blink server lazily started? If so, perhaps that's why only the first plot has issues. 

That's the only think I can think of off the top of my head that would cause the first plot to behave differently from any other plot.

**Comment by tbreloff** [comment]
FWIW I have seen the same behavior... occasionally the first plot doesn't load, likely due to a race condition of some sort.

**Comment by malmaud** [comment]
I've seen this too

**Comment by MikeInnes** [comment]
Yeah we changed it to lazy starting recently. Though I think it should be waiting for it to start before opening the first window. Could try removing the lazy load and see if that helps?

**Comment by spencerlyon2** [comment]
Ok thanks for the heads up  is there a way I can have the server start from my `__init__` function in plotlyjs.jl, or do I have to change things in blink?

**Comment by MikeInnes** [comment]
Should be able to call [this function](https://github.com/JunoLab/Blink.jl/blob/408244b3f62b5d8f03615a1bb82fd3e312ade130/src/content/server.jl#L75). I guess we need to modify that to return once the listening event is fired, or something.

**Comment by malmaud** [comment]
If there's a race condition though, we should really be trying to fix the underlying issue instead of just making the server start faster to reduce its frequency.

**Comment by spencerlyon2** [comment]
I think what @MikeInnes suggested (return once listening event is fired) would solve the race condition @malmaud talks about. Does that seem right?

If so, it would be _great_ to see that.

**Comment by sglyon** [comment]
Closing as this has been inactive for almost a year. Please reopen if this is still an issue.
